export const ItemType = {
	None: 0,
	Clothes: 1,
	Weapons: 2,
	MeleeWeapons: 3,
	Ammo: 4,
	Alco: 5,
	Eat: 6,
	Water: 7,
	Modification: 8,
	Cases: 9,
}

export const ItemId = {
	Debug: 0,
	HealthKit: 1,
	GasCan: 2,
	Crisps: 3,
	Beer: 4,
	Pizza: 5,
	Burger: 6,
	HotDog: 7,
	Sandwich: 8,
	eCola: 9,
	Sprunk: 10,
	Lockpick: 11,
	BagWithMoney: 12,
	Material: 13,
	Drugs: 14,
	BagWithDrill: 15,
	ArmyLockpick: 16,
	Pocket: 17,
	Cuffs: 18,
	CarKey: 19,
	RusDrink1: 20,
	RusDrink2: 21,
	RusDrink3: 22,
	YakDrink1: 23,
	YakDrink2: 24,
	YakDrink3: 25,
	LcnDrink1: 26,
	LcnDrink2: 27,
	LcnDrink3: 28,
	ArmDrink1: 29,
	ArmDrink2: 30,
	ArmDrink3: 31,
	Present: 40,
	KeyRing: 41,
	Pistol: 100,
	CombatPistol: 101,
	Pistol50: 102,
	SNSPistol: 103,
	HeavyPistol: 104,
	VintagePistol: 105,
	MarksmanPistol: 106,
	Revolver: 107,
	APPistol: 108,
	StunGun: 109,
	FlareGun: 110,
	DoubleAction: 111,
	PistolMk2: 112,
	SNSPistolMk2: 113,
	RevolverMk2: 114,
	MicroSMG: 115,
	MachinePistol: 116,
	SMG: 117,
	AssaultSMG: 118,
	CombatPDW: 119,
	MG: 120,
	CombatMG: 121,
	Gusenberg: 122,
	MiniSMG: 123,
	SMGMk2: 124,
	CombatMGMk2: 125,
	AssaultRifle: 126,
	CarbineRifle: 127,
	AdvancedRifle: 128,
	SpecialCarbine: 129,
	BullpupRifle: 130,
	CompactRifle: 131,
	AssaultRifleMk2: 132,
	CarbineRifleMk2: 133,
	SpecialCarbineMk2: 134,
	BullpupRifleMk2: 135,
	SniperRifle: 136,
	HeavySniper: 137,
	MarksmanRifle: 138,
	HeavySniperMk2: 139,
	MarksmanRifleMk2: 140,
	PumpShotgun: 141,
	SawnOffShotgun: 142,
	BullpupShotgun: 143,
	AssaultShotgun: 144,
	Musket: 145,
	HeavyShotgun: 146,
	DoubleBarrelShotgun: 147,
	SweeperShotgun: 148,
	PumpShotgunMk2: 149,
	RayPistol: 150,
	CeramicPistol: 151,
	NavyRevolver: 152,
	RayCarbine: 153,
	GrenadeLauncher: 154,
	RPG: 155,
	Minigun: 156,
	Firework: 157,
	Railgun: 158,
	HomingLauncher: 159,
	GrenadeLauncherSmoke: 160,
	CompactGrenadeLauncher: 161,
	Widowmaker: 162,
	Knife: 180,
	Nightstick: 181,
	Hammer: 182,
	Bat: 183,
	Crowbar: 184,
	GolfClub: 185,
	Bottle: 186,
	Dagger: 187,
	Hatchet: 188,
	KnuckleDuster: 189,
	Machete: 190,
	Flashlight: 191,
	SwitchBlade: 192,
	PoolCue: 193,
	Wrench: 194,
	BattleAxe: 195,
	PistolAmmo: 200,
	SMGAmmo: 201,
	RiflesAmmo: 202,
	SniperAmmo: 203,
	ShotgunsAmmo: 204,
	Snowball: 205,
	cVarmod: 206,
	cClip: 207,
	cSuppressor: 208,
	cScope: 209,
	cMuzzlebrake: 210,
	cBarrel: 211,
	cFlashlight: 212,
	cGrip: 213,
	cCamo: 214,
	HalloweenCoin: 215,
	Firework1: 216,
	Firework2: 217,
	Firework3: 218,
	Firework4: 219,
	CarCoupon: 220,
	MerryChristmasCoin: 221,
	Bear: 222,
	Note: 223,
	LoveNote: 224,
	Vape: 225,
	Rose: 226,
	Barbell: 227,
	Binoculars: 228,
	Bong: 229,
	Umbrella: 230,
	Camera: 231,
	Microphone: 232,
	Guitar: 233,
	Pickaxe1: 234,
	Pickaxe2: 235,
	Pickaxe3: 236,
	Coal: 237,
	Iron: 238,
	Gold: 239,
	Sulfur: 240,
	Emerald: 241,
	Ruby: 242,
	Radio: 243,
	WorkAxe: 244,
	WoodOak: 245,
	WoodMaple: 246,
	WoodPine: 247,
	Boombox: 248,
	Hookah: 249,
	Case0: 250,
	Case1: 251,
	Case2: 252,
	Case3: 253,
	Case4: 254,
	Case5: 255,
	Case6: 256,
	Case7: 257,
	Case8: 258,
	Case9: 259,
	Case10: 260,
	Case11: 261,
	Case12: 262,
	Ball: 263,
	SummerCoin: 264,
	Case13: 265,
	MilitaryRifle: 266,
	CandyCane: 267,
	Case14: 268,
	Qr: 269,
	QrFake: 270,
	SimCard: 271,
	VehicleNumber: 272,
	Bint: 273,
	Cocaine: 274,
	Rub100: 275,
	Rub200: 276,
	Rub500: 277,
	Rub1000: 278,
	RadioInterceptor: 279,
	Epinephrine: 280,
	Case15: 281,
	Case16: 282,
	Case17: 283,
	Case18: 284,
	Case19: 285,
	Case20: 286,
	Case21: 287,
	AppleCoin: 288,
	Fire: 289,
	Matras: 290,
	Tent: 291,
	Lezhak: 292,
	Towel: 293,
	Flag: 294,
	Barrell: 295,
	Surf: 296,
	Vedro: 297,
	Flagstok: 298,
	Tenttwo: 299,
	Polotence: 300,
	Beachbag: 301,
	Zontik: 302,
	Zontiktwo: 303,
	Zontikthree: 304,
	Closedzontik: 305,
	Vball: 306,
	Bball: 307,
	Boomboxxx: 308,
	Table: 309,
	Tabletwo: 310,
	Tablethree: 311,
	Tablefour: 312,
	Chair: 313,
	Chairtwo: 314,
	Chaierthree: 315,
	Chaierfour: 316,
	Chairtable: 317,
	Korzina: 318,
	Light: 319,
	Alco: 320,
	Alcotwo: 321,
	Alcothree: 322,
	Alcofour: 323,
	Cocktail: 324,
	Cocktailtwo: 325,
	Fruit: 326,
	Fruittwo: 327,
	Packet: 328,
	Buter: 329,
	Patatoes: 330,
	Coffee: 331,
	Podnosfood: 332,
	Bbqtwo: 333,
	Bbq: 334,
	Vaza: 335,
	Flagwtokk: 336,
	Flagau: 337,
	Flagbr: 338,
	Flagch: 339,
	Flagcz: 340,
	Flageng: 341,
	Flageu: 342,
	Flagfr: 343,
	Flagger: 344,
	Flagire: 345,
	Flagisr: 346,
	Flagit: 347,
	Flagjam: 348,
	Flagjap: 349,
	Flagmex: 350,
	Flagnet: 351,
	Flagnig: 352,
	Flagnorw: 353,
	Flagpol: 354,
	Flagrus: 355,
	Flagbel: 356,
	Flagscot: 357,
	Flagscr: 358,
	Flagslovak: 359,
	Flagslov: 360,
	Flagsou: 361,
	Flagspain: 362,
	Flagswede: 363,
	Flagswitz: 364,
	Flagturk: 365,
	Flaguk: 366,
	Flagus: 367,
	Flagwales: 368,
	Flagfin: 369,
	Flowerrr: 370,
	Konus: 371,
	Konuss: 372,
	Otboynik1: 373,
	Otboynik2: 374,
	Dontcross: 375,
	Stop: 376,
	NetProezda: 377,
	Kpp: 378,
	Zabor1: 379,
	Zabor2: 380,
	Airlight: 381,
	Camera1: 382,
	Camera2: 383,
	TacticalRifle: 384,
	PrecisionRifle: 385,
	CombatShotgun: 386,
	HeavyRifle: 387,
	NeonStick: 388,
	GlowStick: 389,
	Bracelets: -15,
	Watches: -14,
	Glasses: -13,
	Hat: -12,
	Top: -11,
	Decals: -10,
	BodyArmor: -9,
	Undershit: -8,
	Jewelry: -7,
	Feet: -6,
	Bag: -5,
	Leg: -4,
	Gloves: -3,
	Ears: -2,
	Mask: -1
}

export const itemsInfo = {
	[ItemId.Mask]: {"Name":"Mask","Description":"The mask helps in concealing one's identity while also serving as an ornament. However, it can be foiled by a policeman.","Icon":"inv-item-mask","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Gloves]: {"Name":"Gloves","Description":"They'll keep you warm in the cold winter.","Icon":"inv-item-glove","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Ears]: {"Name":"Headphones","Description":"Headphones are wearable audio devices that envelop the ears, delivering immersive sound.","Icon":"inv-item-ears","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Leg]: {"Name":"Pants","Description":"They'll keep you from freezing.","Icon":"inv-item-shorts","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Bag]: {"Name":"Bag","Description":"Allows you to carry extra items.","Icon":"inv-item-backpack","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Feet]: {"Name":"Footwear","Description":"A modern shoe that will never let you down.","Icon":"inv-item-sneakers","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Jewelry]: {"Name":"Accessories","Description":"Allows you to improve the appearance of the character.","Icon":"inv-item-necklace","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Undershit]: {"Name":"Underwear","Description":"Can be worn under outerwear, gives a stylish look to your character.","Icon":"inv-item-shirt","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.BodyArmor]: {"Name":"Bulletproof Vest","Description":"Serves as a means of protecting you. Able to absorb 100 damage before it breaks.","Icon":"inv-item-armor","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Decals]: {"Name":"Decorations","Description":"Allow you to improve your appearance.","Icon":"inv-item-clock","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Top]: {"Name":"Outerwear","Description":"Can be worn over underwear, gives a stylish look to your character.","Icon":"inv-item-jacket","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Hat]: {"Name":"Hat","Description":"It will save you from sunstroke on a hot day.","Icon":"inv-item-cap","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Glasses]: {"Name":"Glasses","Description":"Protects from the sun on the sunniest day.","Icon":"inv-item-glasses","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Bracelets]: {"Name":"Bracelet","Description":"Allow you to improve your appearance.","Icon":"inv-item-bracelet","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Watches]: {"Name":"Watch","Description":"Shows the status of your character.","Icon":"inv-item-clock","Type":"Clothes","Stack":1,"functionType":1},
	[ItemId.Debug]: {"Name":"None","Description":"","Icon":"","Type":"","Stack":0,"functionType":0},
	[ItemId.BagWithDrill]: {"Name":"Bag with a Drill","Description":"Used to break into the vault.","Icon":"inv-item-Bag-drill","Type":"Remainder","Stack":1,"functionType":0},
	[ItemId.GasCan]: {"Name":"Canister","Description":"Used to refuel the vehicle.","Icon":"inv-item-gasoline","Type":"Tools","Stack":2,"functionType":0},
	[ItemId.Crisps]: {"Name":"Chips","Description":"Snack, restores 30% of health.","Icon":"inv-item-Chips","Type":"Meal","Stack":4,"functionType":6},
	[ItemId.Beer]: {"Name":"Beer","Description":"A lovely refreshment!","Icon":"inv-item-beer","Type":"Water","Stack":5,"functionType":7},
	[ItemId.Pizza]: {"Name":"Pizza","Description":"Mmm... Pizza... Restores 30% of health.","Icon":"inv-item-pizza","Type":"Meal","Stack":3,"functionType":6},
	[ItemId.Burger]: {"Name":"Burger","Description":"A bun with meat, restores 30% of health.","Icon":"inv-item-burger","Type":"Meal","Stack":4,"functionType":6},
	[ItemId.HotDog]: {"Name":"Hot Dog","Description":"A bun with meat, restores 30% of health.","Icon":"inv-item-hot-dog","Type":"Meal","Stack":5,"functionType":6},
	[ItemId.Sandwich]: {"Name":"Sandwich","Description":"A few slices of bread and meat, restores 30% of health.","Icon":"inv-item-sandwich","Type":"Meal","Stack":7,"functionType":6},
	[ItemId.eCola]: {"Name":"Cola","Description":"Non-alcoholic carbonated drink, restores 10% of health.","Icon":"inv-item-eCola","Type":"Water","Stack":5,"functionType":7},
	[ItemId.Sprunk]: {"Name":"Sprunk","Description":"Highly carbonated soft drink, restores 10% of health.","Icon":"inv-item-eCola","Type":"Water","Stack":5,"functionType":7},
	[ItemId.Lockpick]: {"Name":"Lockpick","Description":"A tool for opening locks without a key.","Icon":"inv-item-picklock","Type":"Tool","Stack":10,"functionType":0},
	[ItemId.BagWithMoney]: {"Name":"Money Bag","Description":"Where you can put all the money after a 24/7 robbery.","Icon":"inv-item-briefcase","Type":"Remainder","Stack":1,"functionType":0},
	[ItemId.Material]: {"Name":"Materials","Description":"They are needed to create weapons and ammunition.","Icon":"inv-item-fraction","Type":"Remainder","Stack":4000,"functionType":0},
	[ItemId.Drugs]: {"Name":"Drugs","Description":"Magic tea imposes the effect of narcotic intoxication.","Icon":"inv-item-marijuana","Type":"Remainder","Stack":50,"functionType":0},
	[ItemId.HealthKit]: {"Name":"First Aid Kit","Description":"Needed for treatment, can be used 1 time in 5 minutes.","Icon":"inv-item-medical-kit","Type":"Remainder","Stack":10,"functionType":0},
	[ItemId.ArmyLockpick]: {"Name":"Military Lock Pick","Description":"A tool for opening locks of military vehicles and crates.","Icon":"inv-item-picklock","Type":"Tool","Stack":10,"functionType":0},
	[ItemId.Pocket]: {"Name":"Bag","Description":"An ordinary bag. They say you can put it on someone's head...","Icon":"inv-item-bag","Type":"Tool","Stack":5,"functionType":0},
	[ItemId.Cuffs]: {"Name":"Ties","Description":"Allows you to tie a person with raised hands.","Icon":"inv-item-stretching","Type":"Tool","Stack":5,"functionType":0},
	[ItemId.CarKey]: {"Name":"Car Keys","Description":"A tool that allows you to open/close the car and start it.","Icon":"inv-item-key","Type":"Tool","Stack":1,"functionType":0},
	[ItemId.Present]: {"Name":"Gift","Description":"Contains something interesting! Open it fast!","Icon":"inv-item-gift","Type":"Tool","Stack":1,"functionType":0},
	[ItemId.KeyRing]: {"Name":"Keychain","Description":"Collect all your keys in one big bundle and save space in your pockets!","Icon":"inv-item-key-2","Type":"Tool","Stack":1,"functionType":0},
	[ItemId.RusDrink1]: {"Name":"<On a lemon peel>","Description":"An alcoholic drink with notes of lemon, imposes the effect of alcoholic intoxication.","Icon":"inv-item-On-lemon-peel","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.RusDrink2]: {"Name":"<On lingonberries>","Description":"An alcoholic drink with a slight hint of lingonberries, imposes the effect of alcoholic intoxication.","Icon":"inv-item-The-cranberries","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.RusDrink3]: {"Name":"<Russian Standard>","Description":"Good old Russian vodka, imposes the effect of alcoholic intoxication.","Icon":"inv-item-Russian-standard","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.YakDrink1]: {"Name":"<Asahi>","Description":"Beer with a low malt content, imposes the effect of alcoholic intoxication.","Icon":"inv-item-Asahi","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.YakDrink2]: {"Name":"<Midori>","Description":"Sweet melon liqueur, imposes the effect of alcoholic intoxication.","Icon":"inv-item-Midori","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.YakDrink3]: {"Name":"<Yamazaki>","Description":"Japanese whiskey, imposes the effect of alcoholic intoxication.","Icon":"inv-item-Yamazaki","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.LcnDrink1]: {"Name":"<Martini Asti>","Description":"Sparkling wine, imposes the effect of alcoholic intoxication.","Icon":"inv-item-Martini-Asti","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.LcnDrink2]: {"Name":"<Sambuca>","Description":"A strong liqueur with a pleasant aniseed taste, imposes the effect of alcoholic intoxication.","Icon":"inv-item-Sambuca","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.LcnDrink3]: {"Name":"<Campari>","Description":"Bitter liqueur mixed with aromatic herbs and fruits.","Icon":"inv-item-Campari","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.ArmDrink1]: {"Name":"<Jeevan>","Description":"Armenian cognac, imposes the effect of alcoholic intoxication.","Icon":"inv-item-alcohol","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.ArmDrink2]: {"Name":"<Ararat>","Description":"Armenian cognac with fruity and floral notes, imposes the effect of alcoholic intoxication.","Icon":"inv-item-ararat","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.ArmDrink3]: {"Name":"<Noyan Tapan>","Description":"Armenian wine, imposes the effect of alcoholic intoxication.","Icon":"inv-item-Noyan-Tapan","Type":"Alcohol","Stack":5,"functionType":5},
	[ItemId.Pistol]: {"Name":"Pistol","Description":"A standard pistol, the clip holds 12 rounds.","Icon":"inv-item-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CombatPistol]: {"Name":"Combat Pistol","Description":"A combat pistol, the clip holds 12 rounds.","Icon":"inv-item-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Pistol50]: {"Name":"Pistol 50","Description":"A powerful 0.50 caliber pistol, the clip holds 9 rounds.","Icon":"inv-item-Pistol-50","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SNSPistol]: {"Name":"SNS Pistol","Description":"Pocket pistol 0.25 caliber, the clip holds 6 rounds.","Icon":"inv-item-SNS-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HeavyPistol]: {"Name":"Heavy Pistol","Description":"A heavy pistol, the clip holds 18 rounds.","Icon":"inv-item-Heavy-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.VintagePistol]: {"Name":"Vintage Pistol","Description":"Vintage pistol, the clip holds 7 rounds.","Icon":"inv-item-Vintage-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MarksmanPistol]: {"Name":"Marksman Pistol","Description":"A Marksman pistol, the clip holds 1 cartridge.","Icon":"inv-item-Marksman-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Revolver]: {"Name":"Revolver","Description":"Revolver, the clip holds 6 rounds.","Icon":"inv-item-Heavy-Revolver","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.APPistol]: {"Name":"AP Pistol","Description":"Armor-piercing pistol, the clip holds 18 rounds.","Icon":"inv-item-AP-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.StunGun]: {"Name":"Stun Gun","Description":"Electroshock weapon, the clip holds 1 charge.","Icon":"inv-item-Stun-Gun","Type":"Melee Weapons","Stack":1,"functionType":2},
	[ItemId.FlareGun]: {"Name":"Flare Gun","Description":"A signal gun.","Icon":"inv-item-Flare-Gun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.DoubleAction]: {"Name":"Double Action Revolver","Description":"Self-cocking revolver, the clip holds 6 rounds.","Icon":"inv-item-Double-Action-Revolver","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.PistolMk2]: {"Name":"Pistol Mk2","Description":"An improved version of a conventional pistol, the clip holds 12 rounds.","Icon":"inv-item-Pistol-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SNSPistolMk2]: {"Name":"SNSPistol Mk2","Description":"An improved version of the pocket pistol, the clip holds 6 rounds.","Icon":"inv-item-SNS-Pistol-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.RevolverMk2]: {"Name":"Heavy Revolver Mk2","Description":"An improved version of the standard revolver, the clip holds 6 rounds.","Icon":"inv-item-Heavy-Revolver-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MicroSMG]: {"Name":"Micro SMG","Description":"A small-sized submachine gun, the clip holds 16 rounds.","Icon":"inv-item-Micro-SMG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MachinePistol]: {"Name":"Machine Pistol","Description":"Automatic pistol, the clip holds 12 rounds.","Icon":"inv-item-Machine-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SMG]: {"Name":"SMG","Description":"Submachine gun, the clip holds 30 rounds.","Icon":"inv-item-SMG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.AssaultSMG]: {"Name":"Assault SMG","Description":"Assault automatic weapon, the clip holds 30 rounds.","Icon":"inv-item-Assault-SMG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CombatPDW]: {"Name":"Combat PDW","Description":"A small-sized assault rifle, the clip holds 30 rounds.","Icon":"inv-item-Combat-PDW","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MG]: {"Name":"MG","Description":"Heavy machine gun, the clip holds 54 rounds.","Icon":"inv-item-MG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CombatMG]: {"Name":"Combat MG","Description":"A special purpose machine gun, the clip holds 100 rounds.","Icon":"inv-item-Combat-MG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Gusenberg]: {"Name":"Gusenberg","Description":"Submachine gun, the clip holds 30 rounds.","Icon":"inv-item-Gusenberg-Sweeper","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MiniSMG]: {"Name":"Mini SMG","Description":"A small-sized submachine gun, the clip holds 20 rounds.","Icon":"inv-item-Mini-SMG","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SMGMk2]: {"Name":"SMG Mk2","Description":"Improved submachine gun, the clip holds 30 rounds.","Icon":"inv-item-SMG-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CombatMGMk2]: {"Name":"Combat MG Mk2","Description":"Updated single machine gun, holds 100 rounds.","Icon":"inv-item-Combat-MG-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.AssaultRifle]: {"Name":"Assault Rifle","Description":"Assault rifle, the clip holds 30 rounds.","Icon":"inv-item-Assault-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CarbineRifle]: {"Name":"Carbine Rifle","Description":"American semi-automatic rifle, the clip holds 30 rounds.","Icon":"inv-item-Carbine-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.AdvancedRifle]: {"Name":"Advanced Rifle","Description":"An improved assault rifle, the clip holds 30 rounds.","Icon":"inv-item-Advanced-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SpecialCarbine]: {"Name":"Special Carbine","Description":"An assault rifle with less recoil, the clip holds 30 rounds.","Icon":"inv-item-Special-Carbine","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.BullpupRifle]: {"Name":"Bullpup Rifle","Description":"Chinese assault rifle, the clip holds 30 rounds.","Icon":"inv-item-Bullpup-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CompactRifle]: {"Name":"Compact Rifle","Description":"A shortened rifle, the clip holds 30 rounds.","Icon":"inv-item-Compact-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.AssaultRifleMk2]: {"Name":"Assault Rifle Mk2","Description":"Improved assault rifle, the clip holds 30 rounds.","Icon":"inv-item-Assault-Rifle-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CarbineRifleMk2]: {"Name":"Carbine Rifle Mk2","Description":"Improved semi-automatic rifle, the clip holds 30 rounds.","Icon":"inv-item-Carbine-Rifle-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SpecialCarbineMk2]: {"Name":"Special Carbine Mk2","Description":"An improved assault rifle with a shorter barrel, the clip holds 30 rounds.","Icon":"inv-item-Special-Carbine-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.BullpupRifleMk2]: {"Name":"Bullpup Rifle Mk2","Description":"An improved assault rifle from China, the clip holds 30 rounds.","Icon":"inv-item-Bullpup-Rifle-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MilitaryRifle]: {"Name":"Military Rifle","Description":"An improved assault rifle, the clip holds 30 rounds.","Icon":"inv-item-militaryrifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SniperRifle]: {"Name":"Sniper Rifle","Description":"Sniper rifle, the clip holds 10 rounds.","Icon":"inv-item-Sniper-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HeavySniper]: {"Name":"Heavy Sniper","Description":"A large-caliber sniper rifle, the clip holds 6 rounds.","Icon":"inv-item-Heavy-Sniper","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MarksmanRifle]: {"Name":"Marksman Rifle","Description":"Marksman sniper rifle, the clip holds 8 rounds.","Icon":"inv-item-Marksman-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HeavySniperMk2]: {"Name":"Heavy Sniper Mk2","Description":"Improved large-caliber sniper rifle, the clip holds 6 rounds.","Icon":"inv-item-Heavy-Sniper-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.MarksmanRifleMk2]: {"Name":"Marksman Rifle Mk2","Description":"Improved Marksman sniper rifle, the clip holds 8 rounds.","Icon":"inv-item-Marksman-Rifle-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.PumpShotgun]: {"Name":"Pump Shotgun","Description":"Tactical combat pump-action shotgun, the clip holds 8 rounds.","Icon":"inv-item-Pump-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SawnOffShotgun]: {"Name":"SawnOff Shotgun","Description":"Sawed-off, the clip holds 8 rounds.","Icon":"inv-item-Sawed-Off-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.BullpupShotgun]: {"Name":"Bullpup Shotgun","Description":"Pump-action shotgun, the clip holds 14 rounds.","Icon":"inv-item-Bullpup-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.AssaultShotgun]: {"Name":"Assault Shotgun","Description":"Assault shotgun, the clip holds 8 rounds.","Icon":"inv-item-Assault-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Musket]: {"Name":"Musket","Description":"A hand-held firearm, the clip holds 1 cartridge.","Icon":"inv-item-Musket","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HeavyShotgun]: {"Name":"Heavy Shotgun","Description":"Heavy six-shot shotgun, the clip holds 6 rounds.","Icon":"inv-item-Heavy-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.DoubleBarrelShotgun]: {"Name":"Double Barrel Shotgun","Description":"Double-barreled shotgun, the clip holds 2 rounds.","Icon":"inv-item-Double-Barrel-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.SweeperShotgun]: {"Name":"Sweeper Shotgun","Description":"Compact rapid-fire shotgun, the clip holds 10 rounds.","Icon":"inv-item-Sweeper-Shotgun","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.PumpShotgunMk2]: {"Name":"Pump Shotgun Mk2","Description":"Improved pump-action shotgun, the clip holds 8 rounds.","Icon":"inv-item-Pump-Shotgun-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.RayPistol]: {"Name":"Up-n-Atomizer","Description":"Futuristic pistol, similar in appearance to an alien pistol, does not require ammunition.","Icon":"inv-item-Vintage-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CeramicPistol]: {"Name":"Ceramic Pistol","Description":"Ceramic pistol, the clip holds 12 rounds.","Icon":"inv-item-Combat-Pistol","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.NavyRevolver]: {"Name":"Navy Revolver","Description":"An army revolver, the clip holds 6 rounds.","Icon":"inv-item-Heavy-Revolver-Mk-II","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.RayCarbine]: {"Name":"Unholy Hellbringer","Description":"Futuristic plasma rifle, has an unusual appearance.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.GrenadeLauncher]: {"Name":"Grenade Launcher","Description":"A light grenade launcher with semi-automatic functionality, accommodates up to 10 rounds of ammunition.","Icon":"","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.RPG]: {"Name":"RPG","Description":"Hand-held anti-tank grenade launcher, accommodates 1 ammunition.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Minigun]: {"Name":"Minigun","Description":"6-barrel machine gun, has a very high rate of fire, and also accommodates 595 ammunition.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Firework]: {"Name":"Firework Launcher","Description":"A launcher for launching fireworks, will help to cheer up or arrange a holiday.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Railgun]: {"Name":"Railgun","Description":"Railgun heavy weapon, has a lot of damage, and also holds up to 20 ammunition.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HomingLauncher]: {"Name":"Homing Launcher","Description":"A rocket launcher with infrared targeting, accommodates 1 munition.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.GrenadeLauncherSmoke]: {"Name":"Grenade Launcher Smoke","Description":"Light grenade launcher, launches smoke grenades instead of conventional ones.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CompactGrenadeLauncher]: {"Name":"Compact Grenade Launcher","Description":"Compact grenade launcher, accommodates only 1 ammunition.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Widowmaker]: {"Name":"Widowmaker","Description":"Futuristic plasma machine gun, holds up to 9999 rounds of ammunition.","Icon":"NEEDTEXT","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Knife]: {"Name":"Knife","Description":"A sharp knife that you can cut yourself with.","Icon":"inv-item-Knife","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.Nightstick]: {"Name":"Baton","Description":"Have you found a troublemaker? It's time to use the baton.","Icon":"inv-item-Nightstick","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.Hammer]: {"Name":"Hammer","Description":"The hammer will help you with household chores.","Icon":"inv-item-Hammer","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.Bat]: {"Name":"Baseball Bat","Description":"The bat is great for playing baseball.","Icon":"inv-item-Baseball-Bat","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.Crowbar]: {"Name":"Crowbar","Description":"Crowbar is one of the most popular tools.","Icon":"inv-item-crowbar","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.GolfClub]: {"Name":"Golf Club","Description":"It will allow you to have a great time on the golf course.","Icon":"inv-item-Golf-Club","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.Bottle]: {"Name":"Bottle","Description":"A Bottle.","Icon":"inv-item-Broken-Bottle","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.Dagger]: {"Name":"Dagger","Description":"Very well suited for collectors of rare weapons.","Icon":"inv-item-Antique-Cavalry-Dagger","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.Hatchet]: {"Name":"Axe","Description":"Need to chop wood? The axe is great for this.","Icon":"inv-item-Hatchet","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.KnuckleDuster]: {"Name":"Brass Knuckles","Description":"A great helper in street battles.","Icon":"inv-item-Brass-Knuckles","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.Machete]: {"Name":"Machete","Description":"One of the most effective weapons for survival in the wild jungle.","Icon":"inv-item-Machete","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.Flashlight]: {"Name":"Flashlight","Description":"Bright light will help you if you are lost in a dark forest.","Icon":"inv-item-Flashlight","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.SwitchBlade]: {"Name":"Swiss Knife","Description":"Folding knife, will help you in solving many problems.","Icon":"inv-item-Switchblade","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.PoolCue]: {"Name":"Cue","Description":"Perfect for playing billiards.","Icon":"inv-item-Pool-Cue","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.Wrench]: { "Name":"Wrench","Description":"The Wrench is the most reliable assistant if something is broken.","Icon":"inv-item-Pipe-Wrench","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.BattleAxe]: {"Name":"Battle Axe","Description":"Need to chop up enemies? The axe is a great helper in this.","Icon":"inv-item-Battle-Axe","Type":"Melee Weapons","Stack":1,"functionType":3},
	[ItemId.PistolAmmo]: {"Name":"Pistol Ammo","Description":"These cartridges are perfect for your gun.","Icon":"inv-item-ammo-pistol","Type":"Ammo","Stack":100,"functionType":4},
	[ItemId.RiflesAmmo]: {"Name":"Rifle Ammo","Description":"These cartridges are great for assault rifles.","Icon":"inv-item-ammo-average","Type":"Ammo","Stack":250,"functionType":4},
	[ItemId.ShotgunsAmmo]: {"Name":"Shotgun Ammo","Description":"Suitable for any kind of shotguns.","Icon":"inv-item-ammo-shotgun","Type":"Ammo","Stack":50,"functionType":4},
	[ItemId.SMGAmmo]: {"Name":"SMG Ammo","Description":"They will perfectly match your submachine gun and other small-caliber weapons.","Icon":"inv-item-ammo-small","Type":"Ammo","Stack":300,"functionType":4},
	[ItemId.SniperAmmo]: {"Name":"Sniper Ammo","Description":"Suitable for all sniper rifles.","Icon":"inv-item-ammo-sniper","Type":"Ammo","Stack":48,"functionType":4},
	[ItemId.Snowball]: {"Name":"Snow Ball","Description":"Throw it at someone!","Icon":"inv-item-marijuana","Type":"Special","Stack":1,"functionType":2},
	[ItemId.Ball]: {"Name":"Ball","Description":"For playing with a pet.","Icon":"inv-item-ball","Type":"Special","Stack":1,"functionType":2},
	[ItemId.cVarmod]: {"Name":"Coloring for Weapons","Description":"With this component, you can decorate the weapon, making it more attractive in appearance.","Icon":"inv-item-Varmod","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cClip]: {"Name":"Improved Magazine","Description":"The improved magazine will allow you to expand the maximum ammo in the weapon.","Icon":"inv-item-Clips","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cSuppressor]: {"Name":"Silencer","Description":"A silencer, being mounted on a weapon, muffles the sound of shots and allows you to make silent kills.","Icon":"inv-item-Suppressors","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cScope]: {"Name":"Gun Scope","Description":"The scope will allow the owner of the weapon to aim at his enemies more accurately (Use the mouse wheel).","Icon":"inv-item-Scopes","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cMuzzlebrake]: {"Name":"Muzzle","Description":"This component reduces the recoil of the weapon.","Icon":"inv-item-Muzzle-Brakes","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cBarrel]: {"Name":"Barrel","Description":"The improved barrel on the weapon allows you to increase the accuracy and damage from the weapon.","Icon":"inv-item-Barrels","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cFlashlight]: {"Name":"Weapon Flashlight","Description":"A flashlight mounted on a weapon is a great way to find your enemies in the dark. (Press E to turn it on).","Icon":"inv-item-Flashlights","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cGrip]: {"Name":"Grip","Description":"The improved handle of the weapon provides more comfortable shooting.","Icon":"inv-item-Grips","Type":"Special","Stack":1,"functionType":8},
	[ItemId.cCamo]: {"Name":"Weapon Camo","Description":"With the help of colors, you can diversify the appearance of weapons.","Icon":"inv-item-Varmod","Type":"Special","Stack":1,"functionType":8},
	[ItemId.HalloweenCoin]: {"Name":"Halloween Coin","Description":"A Halloween coin which you can use to get special prizes throughout the event.","Icon":"inv-item-EventCoin","Type":"Special","Stack":999999,"functionType":0},
	[ItemId.Firework1]: {"Name":"Ordinary Fireworks","Description":"Beautiful fireworks.","Icon":"inv-item-Firework1","Type":"Entertainment","Stack":1,"functionType":0},
	[ItemId.Firework2]: {"Name":"Star Fireworks","Description":"Beautiful fireworks in the form of a star.","Icon":"inv-item-Firework2","Type":"Entertainment","Stack":1,"functionType":0},
	[ItemId.Firework3]: {"Name":"Explosive Fireworks","Description":"Beautiful fireworks in the form of an explosion.","Icon":"inv-item-Firework3","Type":"Entertainment","Stack":1,"functionType":0},
	[ItemId.Firework4]: {"Name":"Fireworks Fountain","Description":"Beautiful fireworks in the form of a fountain.","Icon":"inv-item-Firework4","Type":"Entertainment","Stack":1,"functionType":0},
	[ItemId.CarCoupon]: {"Name":"Car Coupon","Description":"Contains a car that will be delivered to the garage after activation.","Icon":"inv-item-car","Type":"Coupons","Stack":1,"functionType":0},
	[ItemId.MerryChristmasCoin]: {"Name":"Christmas Coin","Description":"A Christmas coin which you can use to get special prizes throughout the event.","Icon":"inv-item-EventCoin","Type":"Special","Stack":999999,"functionType":0},
	[ItemId.Bear]: {"Name":"Bear","Description":"Give it to a nice person!","Icon":"inv-item-teddy-bear","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Note]: {"Name":"Note","Description":"With the help of a note, you can leave a message, pass some secret or other important information.","Icon":"inv-item-Note","Type":"Special","Stack":1,"functionType":0},
	[ItemId.LoveNote]: {"Name":"Love Note","Description":"A valentine card will help you describe your warm feelings for a person.","Icon":"inv-item-LoveNote","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Vape]: {"Name":"Vape","Description":"The taste of juicy vaping always lifts the mood.","Icon":"inv-item-Vape","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Rose]: {"Name":"Rose","Description":"A wonderful gift for a loved one!","Icon":"inv-item-rose","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Barbell]: {"Name":"Barbell","Description":"For those who want to trim their aesthetics.","Icon":"inv-item-barbell","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Binoculars]: {"Name":"Binoculars","Description":"Allows you to see objects at a great distance.","Icon":"inv-item-binoculars","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Bong]: {"Name":"Bong","Description":"A convenient device for smoking weed.","Icon":"inv-item-bong","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Umbrella]: {"Name":"Umbrella","Description":"It will allow you to hide from the rain.","Icon":"inv-item-umbrella","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Camera]: {"Name":"Camera","Description":"Light... Camera... Action!","Icon":"inv-item-camera","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Microphone]: {"Name":"Microphone","Description":"Used to amplify your voice.","Icon":"inv-item-microphone","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Guitar]: {"Name":"Guitar","Description":"It's begging to be picked up... Play something!","Icon":"inv-item-guitar","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Pickaxe1]: {"Name":"Ordinary Pickaxe","Description":"You can use this to work in a mine.","Icon":"inv-item-pickaxe1","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Pickaxe2]: {"Name":"Reinforced Pickaxe","Description":"With this, you can work powerfully at the mine.","Icon":"inv-item-pickaxe2","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Pickaxe3]: {"Name":"Professional Pickaxe","Description":"With this, you can work professionally at the mine.","Icon":"inv-item-pickaxe3","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Coal]: {"Name":"Coal","Description":"Coal from the mine.","Icon":"inv-item-coal","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Iron]: {"Name":"Iron","Description":"Iron from the mine.","Icon":"inv-item-iron","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Gold]: {"Name":"Gold","Description":"Gold from the mine.","Icon":"inv-item-gold","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Sulfur]: {"Name":"Sulfur","Description":"Sulfur from the mine.","Icon":"inv-item-sulfur","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Emerald]: {"Name":"Emerald","Description":"An extremely rare Emerald from the mine.","Icon":"inv-item-emerald","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Ruby]: {"Name":"Ruby","Description":"A very rare Ruby from the mine.","Icon":"inv-item-ruby","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Radio]: {"Name":"Transmitter","Description":"With the help of a walkie-talkie, you can communicate with other owners of a walkie-talkie, or even eavesdrop on a police or other secret wave.","Icon":"hud__icon-walkie-talkie","Type":"Special","Stack":1,"functionType":0},
	[ItemId.WorkAxe]: {"Name":"Work Axe","Description":"A tool for working as a logger.","Icon":"inv-item-workaxe","Type":"Special","Stack":1,"functionType":0},
	[ItemId.WoodOak]: {"Name":"Oak","Description":"Wood.","Icon":"inv-item-woodoak","Type":"Special","Stack":250,"functionType":0},
	[ItemId.WoodMaple]: {"Name":"Maple","Description":"Wood.","Icon":"inv-item-woodmaple","Type":"Special","Stack":250,"functionType":0},
	[ItemId.WoodPine]: {"Name":"Pine","Description":"Wood.","Icon":"inv-item-woodpine","Type":"Special","Stack":250,"functionType":0},
	[ItemId.Boombox]: {"Name":"Boombox","Description":"Allows you to play your music for people around. Rock the party!","Icon":"inv-item-boombox","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Hookah]: {"Name":"Hookah","Description":"A hookah is a water pipe for smoking flavored tobacco, cooled and filtered through a water-filled base.","Icon":"inv-item-hookah","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Case0]: {"Name":"Free Daily Case","Description":"A free case can be obtained after 3 hours of play.","Icon":"inv-item-case0","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case1]: {"Name":"Free Gun Case","Description":"A free case with weapons can be obtained after 5 hours of play.","Icon":"inv-item-case1","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case2]: {"Name":"Free Car Case","Description":"A free case with cars can be obtained after 8 hours of play.","Icon":"inv-item-case2","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case3]: {"Name":"Standard Case","Description":"A standard case with standard prizes.","Icon":"inv-item-case3","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case4]: {"Name":"Strange Case","Description":"Not a bad case for beginners.","Icon":"inv-item-case4","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case5]: {"Name":"Special Case","Description":"Juicy case, there is an opportunity to pay off seriously!","Icon":"inv-item-case5","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case6]: {"Name":"Rare Case","Description":"A case with items and cars of increased rarity.","Icon":"inv-item-case6","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case7]: {"Name":"Fierce Case","Description":"A very fierce case. Super prize - Bugatti, the fastest car.","Icon":"inv-item-case7","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case8]: {"Name":"Men's Case","Description":"A case with men's clothing from a dontation clothing store. Try your luck and be stylish, or sell to someone and be rich. Or you can give it to me...","Icon":"inv-item-case8","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case9]: {"Name":"Women's Case","Description":"A case with women's clothing from a dontation clothing store. A great option if you want to give something.","Icon":"inv-item-case9","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case10]: {"Name":"Exotic Case","Description":"A case with cars from Donate Room Autoroom. Donate RedBucks approves!","Icon":"inv-item-case10","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case11]: {"Name":"Legendary Case","Description":"All or nothing! Do you want to take a chance and become the owner of the legendary Cypress Jacket? Then pop the case!","Icon":"inv-item-case11","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case12]: {"Name":"Interesting Case","Description":"Have you been wanting a unique car that is not for sale anywhere for a long time? You are welcome! Dodge Charger - is in service with the police, has quite high characteristics.","Icon":"inv-item-case12","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case13]: {"Name":"Helicopter Case","Description":"Do you like to look down on people? Perhaps a helicopter would be perfect for this!","Icon":"inv-item-case13","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case14]: {"Name":"Armored Case","Description":"Cool new case of fashionable armored cars!","Icon":"inv-item-case14","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case15]: {"Name":"Exclusive Case","Description":"Cool new case with placeable items!","Icon":"inv-item-case15","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case16]: {"Name":"Snow Case [М]","Description":"An exclusive case from the Battle Pass, it contains several sets of clothes with the same chance of falling out.","Icon":"inv-item-case16","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case17]: {"Name":"Amethyst Case [М]","Description":"An exclusive case from the Battle Pass, it contains several sets of clothes with the same chance of falling out.","Icon":"inv-item-case17","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case18]: {"Name":"Holiday Case [М]","Description":"An exclusive case from the Battle Pass, it contains several sets of clothes with the same chance of falling out.","Icon":"inv-item-case18","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case19]: {"Name":"Snow Case [F]","Description":"An exclusive case from the Battle Pass, it contains several sets of clothes with the same chance of falling out.","Icon":"inv-item-case19","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case20]: {"Name":"Amethyst Case [F]","Description":"An exclusive case from the Battle Pass, it contains several sets of clothes with the same chance of falling out.","Icon":"inv-item-case20","Type":"Special","Stack":100,"functionType":9},
	[ItemId.Case21]: {"Name":"Holiday Case [F]","Description":"An exclusive case from the Battle Pass, it contains several sets of clothes with the same chance of falling out.","Icon":"inv-item-case21","Type":"Special","Stack":100,"functionType":9},
	[ItemId.SummerCoin]: {"Name":"Jaguar Coin","Description":"A coin for which you can get special prizes on the days of the event. IT IS NOT A DONATION CURRENCY!","Icon":"inv-item-EventCoin","Type":"Special","Stack":999999,"functionType":0},
	[ItemId.CandyCane]: {"Name":"Candy Cane","Description":"A Candy Cane, for which you can get special prizes on the days of the event.","Icon":"inv-item-EventCoin","Type":"Special","Stack":999999,"functionType":0},
	[ItemId.Qr]: {"Name":"QR Code","Description":"A QR code containing information about the disease and/or vaccination. Present on demand.","Icon":"inv-item-QR","Type":"Special","Stack":1,"functionType":0},
	[ItemId.QrFake]: {"Name":"Fake QR Code","Description":"A QR code containing information about the disease and/or vaccination. Present on demand.","Icon":"inv-item-QR","Type":"Special","Stack":1,"functionType":0},
	[ItemId.SimCard]: {"Name":"SIM Card","Description":"A SIM card with a phone number. It can be inserted into any modern smartphone and use the cellular network: write SMS, call and much more.","Icon":"inv-item-SimCard","Type":"Special","Stack":1,"functionType":0},
	[ItemId.VehicleNumber]: {"Name":"License Plate","Description":"The license plate of the vehicle. You can install it on your car, sell it or give it to someone!","Icon":"inv-item-SimCard","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Bint]: {"Name":"Bandage","Description":"Bandage, restores 40% of health. It can be used once every 3 minutes.","Icon":"inv-item-SimCard","Type":"Remainder","Stack":10,"functionType":0},
	[ItemId.Cocaine]: {"Name":"Cocaine","Description":"The magic powder imposes the effect of narcotic intoxication.","Icon":"inv-item-SimCard","Type":"Remainder","Stack":10,"functionType":0},
	[ItemId.Rub100]: {"Name":"100 Rubles","Description":"You can exchange this item for real money from the Project Manager!","Icon":"inv-item-SimCard","Type":"Remainder","Stack":1,"functionType":0},
	[ItemId.Rub200]: {"Name":"200 Rubles","Description":"You can exchange this item for real money from the Project Manager!","Icon":"inv-item-SimCard","Type":"Remainder","Stack":1,"functionType":0},
	[ItemId.Rub500]: {"Name":"500 Rubles","Description":"You can exchange this item for real money from the Project Manager!","Icon":"inv-item-SimCard","Type":"Remainder","Stack":1,"functionType":0},
	[ItemId.Rub1000]: {"Name":"1000 Rubles","Description":"You can exchange this item for real money from the Project Manager!","Icon":"inv-item-SimCard","Type":"Remainder","Stack":1,"functionType":0},
	[ItemId.RadioInterceptor]: {"Name":"Radio Interceptor","Description":"Allows you to get data about the Heli Crash.","Icon":"hud__icon-walkie-talkie","Type":"Remainder","Stack":1,"functionType":0},
	[ItemId.Epinephrine]: {"Name":"Epinephrine","Description":"Needed for treatment, can be used 1 time in 5 minutes.","Icon":"inv-item-medical-kit","Type":"Remainder","Stack":10,"functionType":0},
	[ItemId.AppleCoin]: {"Name":"Apple Coin","Description":"A summer coin that can be obtained on the days of the event (F for Apple Pay).","Icon":"inv-item-medical-kit","Type":"Remainder","Stack":999,"functionType":0},
	[ItemId.Fire]: {"Name":"Fire","Description":"Suitable for evening gatherings, do not get burned!","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Matras]: {"Name":"Inflatable Mattress","Description":"For a beach holiday and not to drown.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Tent]: {"Name":"Tent","Description":"For camping, picnicking and a stormy nights.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Lezhak]: {"Name":"Sunbed","Description":"For a beach holiday, you can lie down and think about a bright future.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Towel]: {"Name":"Towel","Description":"For a beach holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flag]: {"Name":"Flag","Description":"Russian flag, do not forget to buy a flagpole.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Barrell]: {"Name":"Barrel","Description":"Suitable for various needs.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Surf]: {"Name":"Surfboard","Description":"For a beach holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Vedro]: {"Name":"Bucket","Description":"For a beach holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagstok]: {"Name":"Sprunk Flag with Flagpole","Description":"Flagpole with a large Sprunk flag attached.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Tenttwo]: {"Name":"Tent","Description":"For camping, picnicking and a stormy night.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Polotence]: {"Name":"Beach Towel","Description":"For a beach holiday","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Beachbag]: {"Name":"Beach Bag","Description":"For a beach holiday","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Zontik]: {"Name":"Umbrella","Description":"Protects from the sun and is suitable for a beach holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Zontiktwo]: {"Name":"Umbrella","Description":"Protects from the sun and is suitable for a beach holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Zontikthree]: {"Name":"Umbrella","Description":"Protects from the sun and is suitable for a beach holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Closedzontik]: {"Name":"Closed Umbrella","Description":"It will not protect from the sun, but it is suitable for a beach holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Vball]: {"Name":"Volleyball","Description":"For fun games and beach holidays.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Bball]: {"Name":"Beach Ball","Description":"For fun games and beach holidays.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Boomboxxx]: {"Name":"Boombox","Description":"Suitable for gatherings with friends.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Table]: {"Name":"Table","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Tabletwo]: {"Name":"Table","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Tablethree]: {"Name":"Table","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Tablefour]: {"Name":"Table","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Chair]: {"Name":"Chair","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Chairtwo]: {"Name":"Chair","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Chaierthree]: {"Name":"Chair","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Chaierfour]: {"Name":"Chair","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Chairtable]: {"Name":"Table and Chair","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Korzina]: {"Name":"Basket","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Light]: {"Name":"Lighting","Description":"Lighting that is useful in the dark.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Alco]: {"Name":"Bottle of Brandy","Description":"An expensive bottle of brandy for fun and a good night with a girl or a guy.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Alcotwo]: {"Name":"Bottle of Cognac","Description":"An expensive bottle of cognac for fun and a good night with a girl or a guy.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Alcothree]: {"Name":"Bottle of Tequila","Description":"An expensive bottle of tequila for fun and a good night with a girl or a guy.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Alcofour]: {"Name":"Bottle of Beer","Description":"Cheap beer, suitable for gatherings with friends in nature.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Cocktail]: {"Name":"Cocktail","Description":"A mixture of citrus fruits and alcohol, perfect for your girlfriend.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Cocktailtwo]: {"Name":"Cocktail","Description":"A mixture of citrus fruits and alcohol, perfect for your girlfriend.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Fruit]: {"Name":"A plate of fruit","Description":"Delicious and fragrant fruit plate.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Fruittwo]: {"Name":"A plate of fruit","Description":"Delicious and fragrant fruit plate.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Packet]: {"Name":"Package","Description":"Suitable for a picnic.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Buter]: {"Name":"Sandwich","Description":"Suitable for a picnic.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Patatoes]: {"Name":"French Fries","Description":"Suitable for a picnic.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Coffee]: {"Name":"Hot Coffee","Description":"Suitable for a picnic.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Podnosfood]: {"Name":"Food Tray","Description":"Suitable for a picnic.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Bbqtwo]: {"Name":"Barbecue","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Bbq]: {"Name":"Big Barbecue","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flowerrr]: {"Name":"Bouquet of Flowers","Description":"A beautiful bouquet with colorful flowers that your lady will like.","Icon":"prop_snow_flower_02","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Vaza]: {"Name":"Vase with Flowers","Description":"A vase with beautiful white flowers that your lady will like.","Icon":"vw_prop_flowers_vase_01a","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagwtokk]: {"Name":"Flagpole","Description":"Suitable for a picnic or a regular holiday.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagau]: {"Name":"Flag of Australia","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_australia","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagbr]: {"Name":"Flag of Brazil","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_brazil","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagch]: {"Name":"Flag of China","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_china","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagcz]: {"Name":"Flag of the Czech Republic","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_czechrep","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flageng]: {"Name":"Flag of England","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_england","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flageu]: {"Name":"Flag of the European Union","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_eu_yt","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagfin]: {"Name":"Flag of Finland","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_finland","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagfr]: {"Name":"Flag of France","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_france","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagger]: {"Name":"Flag of Germany","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_german_yt","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagire]: {"Name":"Flag of Ireland","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_ireland","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagisr]: {"Name":"Flag of Israel","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_israel","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagit]: {"Name":"Flag of Italy","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_italy","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagjam]: {"Name":"Flag of Jamaica","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_jamaica","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagjap]: {"Name":"Flag of Japan","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_japan_yt","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagmex]: {"Name":"Flag of Mexico","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_mexico_yt","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagnet]: {"Name":"Flag of the Netherlands","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_netherlands","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagnig]: {"Name":"Flag of Nigeria","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_nigeria","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagnorw]: {"Name":"Flag of Norway","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_norway","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagpol]: {"Name":"Flag of Poland","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_poland","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagrus]: {"Name":"Flag of Russia","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_russia_yt","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagbel]: {"Name":"Flag of Belgium","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_belgium","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagscot]: {"Name":"Flag of Scotland","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_scotland_yt","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagscr]: {"Name":"Flag Script","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_script","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagslov]: {"Name":"Flag of Slovakia","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_slovakia","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagslovak]: {"Name":"Flag of Slovenia","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_slovenia","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagsou]: {"Name":"Flag of Korea","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_southkorea","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagspain]: {"Name":"Flag of Spain","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_spain","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagswede]: {"Name":"Flag of Sweden","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_sweden","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagswitz]: {"Name":"Flag of Switzerland","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_switzerland","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagturk]: {"Name":"Flag of Turkey","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_turkey","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flaguk]: {"Name":"Flag of Great Britain","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_uk_yt","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagus]: {"Name":"Flag of America","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_us_yt","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Flagwales]: {"Name":"Flag of Wales","Description":"A medium-sized flag, a flagpole is needed for mounting.","Icon":"apa_prop_flag_wales","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Konus]: {"Name":"Cone","Description":"Suitable as a fence.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Konuss]: {"Name":"Glowing Cone","Description":"Suitable as a fence.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Otboynik1]: {"Name":"Bumper","Description":"Suitable as a fence.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Otboynik2]: {"Name":"Bumper","Description":"Suitable as a fence.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Dontcross]: {"Name":"Closure","Description":"Suitable as a fence.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Stop]: {"Name":"STOP Sign","Description":"Suitable for traffic regulations.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.NetProezda]: {"Name":"NO PASSAGE Sign","Description":"Suitable for traffic regulations.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Zabor1]: {"Name":"Big Fence","Description":"Suitable as a fence.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Kpp]: {"Name":"CHECKPOINT","Description":"Suitable for setting up a checkpoint installation.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Zabor2]: {"Name":"Small Fence","Description":"Suitable as a fence","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Airlight]: {"Name":"Night Light","Description":"Suitable as a fence.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Camera1]: {"Name":"Security Camera","Description":"Suitable for observation.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.Camera2]: {"Name":"Security Camera","Description":"Suitable for observation.","Icon":"placingprop","Type":"Placed Items","Stack":1,"functionType":0},
	[ItemId.TacticalRifle]: {"Name":"Tactical Rifle","Description":"An improved assault rifle, the clip holds 30 rounds.","Icon":"inv-item-militaryrifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.PrecisionRifle]: {"Name":"Precision Rifle","Description":"An improved sniper rifle, the clip holds 6 rounds.","Icon":"inv-item-militaryrifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.CombatShotgun]: {"Name":"Combat Shotgun","Description":"An improved shotgun, the clip holds 10 rounds.","Icon":"inv-item-militaryrifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.HeavyRifle]: {"Name":"Heavy Rifle","Description":"An improved assault rifle, the clip holds 30 rounds.","Icon":"inv-item-militaryrifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.NeonStick]: {"Name":"Neon Sticks","Description":"Sticks of red color that you can hold in your hands.","Icon":"inv-item-Assault-Rifle","Type":"Special","Stack":1,"functionType":0},
	[ItemId.GlowStick]: {"Name":"Glow Sticks","Description":"Beautiful glow sticks that you can hold in your hands.","Icon":"inv-item-Assault-Rifle","Type":"Special","Stack":1,"functionType":0},
	[ItemId.Giftcoin]: {"Name":"Gift","Description":"The gift box that Santa hid for you!","Icon":"inv-item-Assault-Rifle","Type":"Special","Stack":999,"functionType":0},
	[ItemId.CombatRifle]: {"Name":"Combat Rifle","Description":"A rifle that demolishes everything in its path.","Icon":"inv-item-Carbine-Rifle","Type":"Weapon","Stack":1,"functionType":2},
	[ItemId.Glock]: {"Name":"Banana Glock","Description":"Banana Glock.","Icon":"inv-item-Carbine-Rifle","Type":"Weapon","Stack":1,"functionType":2}
}