export default {
    hair: {
        true: [
            {id: 1, name: 'Short', price: 1000, creator: false},
            {id: 2, name: 'Hawk', price: 1000, creator: true},
            {id: 3, name: 'Hipster', price: 1000, creator: true},
            {id: 4, name: 'Bangs on the side', price: 1000, creator: false}, 
            {id: 5, name: 'Short', price: 1000, creator: false},
            {id: 6, name: 'Short', price: 1000, creator: true},
            {id: 7, name: 'Tail', price: 1000, creator: false},
            {id: 8, name: 'Pigtails', price: 1000, creator: true},
            {id: 9, name: 'Slick', price: 1000, creator: false},
            {id: 10, name: 'Short', price: 1000, creator: true},
            {id: 11, name: 'Spikes', price: 1000, creator: true},
            {id: 12, name: 'Caesar', price: 1000, creator: false},
            {id: 13, name: 'Choppy', price: 1000, creator: true},
            {id: 14, name: 'Dreadlocks', price: 1000, creator: true},
            {id: 15, name: 'Long', price: 1000, creator: false},
            {id: 16, name: 'Shaggy Curls', price: 1000, creator: false}, 
            {id: 17, name: 'Surfer', price: 1000, creator: false},
            {id: 18, name: 'Sideways', price: 1000, creator: true},
            {id: 19, name: 'Lick', price: 1000, creator: false},
            {id: 20, name: 'Long', price: 1000, creator: false},
            {id: 21, name: 'Young Hipster', price: 1000, creator: true},
            {id: 22, name: 'Broom', price: 1000, creator: true},
            {id: 24, name: 'Classic Pigtails', price: 1000, creator: false},
            {id: 25, name: 'Pigtails - Palm', price: 1000, creator: false},
            {id: 26, name: 'Pigtails - Lightning', price: 1000, creator: false},
            {id: 27, name: 'Pigtails combined at the top', price: 1000, creator: false}, 
            {id: 28, name: 'Pigtails - Zigzags', price: 1000, creator: false},
            {id: 29, name: 'Pigtails - Snail', price: 1000, creator: false},
            {id: 30, name: 'High-top', price: 1000, creator: false},
            {id: 31, name: 'Comb Back', price: 1000, creator: false},
            {id: 32, name: 'Trimmed Comb back', shortname: "Подстр. зачес назад", price: 1000, creator: true},
            {id: 33, name: 'Trimmed side comb', shortname: "Подстр. зачес на бок", price: 1000, creator: true},
            {id: 34, name: 'Spiked Mohawk', price: 1000, creator: false},
            {id: 35, name: 'Stylist', price: 1000, creator: true},
            {id: 36, name: 'Stylist With layers', price: 1000, creator: false},
        ],
        false: [
            {id: 1, name: 'Short', price: 1000, creator: true},
            {id: 2, name: '"layers"', price: 1000, creator: true},
            {id: 3, name: 'Pigtails', price: 1000, creator: true},
            {id: 4, name: 'Tail', price: 1000, creator: true},
            {id: 5, name: 'Mohawk', price: 1000, creator: true},
            {id: 6, name: 'Pigtails', price: 1000, creator: false},
            {id: 7, name: 'Bob', price: 1000, creator: false},
            {id: 8, name: 'Hawk', price: 1000, creator: false},
            {id: 9, name: 'Shell', price: 1000, creator: false},
            {id: 10, name: 'Long Bob', price: 1000, creator: true},
            {id: 11, name: 'Free', price: 1000, creator: true},
            {id: 12, name: 'Pixel', price: 1000, creator: true},
            {id: 13, name: 'Shaved Whiskey', price: 1000, creator: true},
            {id: 14, name: 'Node', price: 1000, creator: false},
            {id: 15, name: 'Wavy Bob', price: 1000, creator: true},
            {id: 16, name: 'Pretty Woman', price: 1000, creator: true},
            {id: 17, name: 'Bunch', price: 1000, creator: true},
            {id: 18, name: 'Flapper Bob"', price: 1000, creator: false},
            {id: 19, name: '"Тугой Node"', price: 1000, creator: false},
            {id: 20, name: '"Dandelion"', price: 1000, creator: true},
            {id: 21, name: '"Blast"', price: 1000, creator: false},
            {id: 22, name: '"Node"', price: 1000, creator: false},
            {id: 25, name: '"Chipped Pigtails"', price: 1000, creator: false},
            {id: 26, name: 'Pigtails - "листья"', price: 1000, creator: false},
            {id: 27, name: 'Pigtails - Zigzags', price: 1000, creator: false},
            {id: 28, name: '"Tailики" с челкой', price: 1000, creator: false},
            {id: 29, name: 'Pigtails - "Waves"', price: 1000, creator: false},
            {id: 30, name: 'Pigtails - curls', price: 1000, creator: false},
            {id: 31, name: 'Headband - roller', price: 1000, creator: false},
            {id: 32, name: 'Растрёпанный зачес назад', price: 1000, creator: false},
            {id: 33, name: 'Trimmed Comb back', price: 1000, creator: true},
            {id: 34, name: 'Подстриженный зачес Sideways', price: 1000, creator: true},
            {id: 35, name: 'Spiked Mohawk', price: 1000, creator: false},
            {id: 36, name: 'Bandana and Pigtails', price: 1000, creator: false},
            {id: 37, name: '"Chelsea"', price: 1000, creator: true},
            {id: 38, name: '"Stylist" With layers', price: 1000, creator: true},
        ]
    },
    eyebrows: [
        {id: 0, name: 'Neat', price: 100, creator: true},
        {id: 1, name: 'Trendy', price: 100, creator: true},
        {id: 2, name: 'Cleopatra', price: 100, creator: false},
        {id: 3, name: 'Ironic', price: 100, creator: true},
        {id: 4, name: 'Feminine', price: 100, creator: false},
        {id: 5, name: 'Seductive', price: 100, creator: false}, 
        {id: 6, name: 'Frowned', price: 100, creator: true},
        {id: 7, name: 'Chick', price: 100, creator: false},
        {id: 8, name: 'Triumphant', price: 100, creator: false},
        {id: 9, name: 'Carefree', price: 100, creator: true},
        {id: 10, name: 'Arc', price: 100, creator: true},
        {id: 11, name: 'Mouse', price: 100, creator: true},
        {id: 12, name: 'Double Cut', price: 100, creator: false},
        {id: 13, name: 'Hollow', price: 100, creator: false},
        {id: 14, name: 'Pencil Drawn', price: 100, creator: false},
        {id: 15, name: 'Plucked', price: 100, creator: false},
        {id: 16, name: 'Straight and Thin', price: 100, creator: false},
        {id: 17, name: 'Natural', price: 100, creator: false},
        {id: 18, name: 'Lush', price: 100, creator: true},
        {id: 19, name: 'Untidy', price: 100, creator: true},
        {id: 20, name: 'Wide', price: 100, creator: false},
        {id: 21, name: 'Ordinary', price: 100, creator: false},
        {id: 22, name: 'Southern European', price: 100, creator: true},
        {id: 23, name: 'Well-groomed', price: 100, creator: true}, 
        {id: 24, name: 'Bushy', price: 100, creator: true},
        {id: 25, name: 'Feathers', price: 100, creator: true},
        {id: 26, name: 'Prickly', price: 100, creator: false},
        {id: 27, name: 'Fused', price: 100, creator: false},
        {id: 28, name: 'Winged', price: 100, creator: false},
        {id: 29, name: 'Triple die-cut', price: 100, creator: true},
        {id: 30, name: 'Cut Arc', price: 100, creator: false},
        {id: 31, name: 'Clipped', price: 100, creator: false},
        {id: 32, name: 'Coming to nothing', price: 100, creator: false}, 
        {id: 33, name: 'Cut', price: 100, creator: false},
    ],
    facialhair: [
        {id: 255, name: "Smooth Skin", price: 100, creator: true},
        {id: 0, name: 'Light Stubble', price: 100, creator: true},
        {id: 1, name: 'Balbo', price: 100, creator: true},
        {id: 2, name: 'Round Beard', price: 100, creator: true},
        {id: 3, name: 'Goatee', price: 100, creator: true},
        {id: 4, name: 'Goatee', price: 100, creator: true},
        {id: 5, name: 'Island', price: 100, creator: true},
        {id: 6, name: 'Thin Beard', price: 100, creator: true},
        {id: 7, name: 'Short Beard', price: 100, creator: true},
        {id: 8, name: 'Musketeer', price: 100, creator: true},
        {id: 9, name: 'Mustache', price: 100, creator: true},
        {id: 10, name: 'Trimmed Beard', price: 100, creator: true},
        {id: 11, name: 'Bristle', price: 100, creator: true},
        {id: 12, name: 'Round Beard', price: 100, creator: true},
        {id: 13 , name: 'Horseshoe Beard', price: 100, creator: false},
        {id: 14, name: 'Pencil Mustache and Sideburns', price: 100, creator: false},
        {id: 15, name: 'Beard-Belt', price: 100, creator: false},
        {id: 16, name: 'Balbo and bucky', price: 100, creator: false},
        {id: 17, name: 'Tanks', price: 100, creator: false},
        {id: 18, name: 'Short Beard', price: 100, creator: false},
        {id: 19, name: 'Dali', price: 100, creator: false},
        {id: 20, name: 'Dali and Beard', price: 100, creator: false},
        {id: 21, name: 'Handlebars', price: 100, creator: false},
        {id: 22, name: 'Island with Mustache', price: 100, creator: false},
        {id: 23, name: 'English Mustache', price: 100, creator: false},
        {id: 24, name: 'Hollywood', price: 100, creator: false},
        {id: 25, name: 'Fu Manchu', price: 100, creator: false},
        {id: 26, name: 'Island with Tanks', price: 100, creator: false},
        {id: 27, name: 'Wide Tanks', price: 100, creator: false},
        {id: 28, name: 'Beard"', price: 100, creator: false},
    ],
    chesthair: [//-
        {id: 255, name: "Smooth Skin", price: 100},
        {id: 0, name: "Natural", price: 100},
        {id: 1, name: "Strip", price: 100},
        {id: 2, name: "Tree", price: 100},
        {id: 3, name: "Hairy", price: 100}, 
        {id: 4, name: "Overgrown", price: 100},
        {id: 5, name: "Monkey", price: 100},
        {id: 6, name: "Combed Monkey", price: 100},
        {id: 7, name: "Bikini", price: 100},
        {id: 8, name: "Lightning", price: 100},
        {id: 9, name: "Reverse Lightning", price: 100},
        {id: 10, name: "Heart", price: 100},
        {id: 11, name: "Mustache", price: 100},
        {id: 12, name: "Smiley Face", price: 100}, 
        {id: 13, name: "Skull", price: 100},
        {id: 14, name: "Path", price: 100},
        {id: 15, name: "Path and Nipples", price: 100}, 
        {id: 16, name: "Hairy Hands", price: 100}
    ],
    blemishes: [
        {id: 255, name: "No"},
        {id: 0, name: "Rubella"},
        {id: 1, name: "Measles"},
        {id: 2, name: "Spots"},
        {id: 3, name: "Rash"},
        {id: 4, name: "Acne"},
        {id: 5, name: "Plaque"},
        {id: 6, name: "Pustules"},
        {id: 7, name: "Pimples"},
        {id: 8, name: "Large Pimples"},
        {id: 9, name: "Pimples"},
        {id: 10, name: "Rash on cheeks"},
        {id: 11, name: "Rash on the face"},
        {id: 12, name: "Uncovered"},
        {id: 13, name: "Puberty"},
        {id: 14, name: "Ulcer"},
        {id: 15, name: "Rash on the jaw"},
        {id: 16, name: "With two faces"},
        {id: 17, name: "Zone T"},
        {id: 18, name: "Greasy Skin"},
        {id: 19, name: "Scars"},
        {id: 20, name: "Acne Scars"},
        {id: 21, name: "Acne Scars"},
        {id: 22, name: "Herpes"},
        {id: 23, name: "Lichen"},
    ],
    ageing: [
        {id: 255, name: "No"},
        {id: 0, name: "Eye Wrinks"},
        {id: 1, name: "Signs of Ageing"},
        {id: 2, name: "Middle Age"},
        {id: 3, name: "Wrinkles"},
        {id: 4, name: "Depression"},
        {id: 5, name: "Elderly"},
        {id: 6, name: "Old Age"},
        {id: 7, name: "Weathered Skin"},
        {id: 8, name: "Wrinkled Skin"},
        {id: 9, name: "Sagging Skin"},
        {id: 10, name: "Hard Life"},
        {id: 11, name: "Vintage"},
        {id: 12, name: "Retired"},
        {id: 13, name: "Addict"},
        {id: 14, name: "Old Age"},
        {id: 15, name: "Depression"}
    ],
    complexion: [
        {id: 255, name: "No"},
        {id: 0, name: "Blush"},
        {id: 1, name: "Bristle Irritation"},
        {id: 2, name: "Redness"},
        {id: 3, name: "Sunburn"},
        {id: 4, name: "Bruises"},
        {id: 5, name: "Alcoholism"},
        {id: 6, name: "Spots"},
        {id: 7, name: "Тотем"},
        {id: 8, name: "Blood Vessels"},
        {id: 9, name: "Damage"},
        {id: 10, name: "Pale"},
        {id: 11, name: "Dead-Pale"}
    ],
    molesfreckles: [
        {id: 255, name: "No"},
        {id: 0, name: "Angel"},
        {id: 1, name: "Everywhere"},
        {id: 2, name: "Places"},
        {id: 3, name: "Single"},
        {id: 4, name: "Bridge of Nose"},
        {id: 5, name: "Doll"},
        {id: 6, name: "Fairy"},
        {id: 7, name: "Tanned"},
        {id: 8, name: "Moles"},
        {id: 9, name: "Row"},
        {id: 10, name: "Like a Model"},
        {id: 11, name: "Rare"},
        {id: 12, name: "Freckles"},
        {id: 13, name: "Droplets"},
        {id: 14, name: "Doubling"},
        {id: 15, name: "One Side"},
        {id: 16, name: "Pairs"},
        {id: 17, name: "Warts"}
    ],
    sundamage: [
        {id: 255, name: "No"},
        {id: 0, name: "Uneven"},
        {id: 1, name: "Emery"},
        {id: 2, name: "Spotted"},
        {id: 3, name: "Rough"},
        {id: 4, name: "Hard"},
        {id: 5, name: "Rough"},
        {id: 6, name: "Roughed up"},
        {id: 7, name: "Uneven"},
        {id: 8, name: "Со folds"},
        {id: 9, name: "Cracks"},
        {id: 10, name: "Solid"}
    ],
    eyescolor: [
        {id: 0, name: 'Green', price: 100},
        {id: 1, name: 'Emerald', price: 100},
        {id: 2, name: 'Blue', price: 100},
        {id: 3, name: 'Blue', price: 100},
        {id: 4, name: 'Light Brown', price: 100},
        {id: 5, name: 'Dark Brown', price: 100},
        {id: 6, name: 'Brown', price: 100},
        {id: 7, name: 'Dark Grey', price: 100},
        {id: 8, name: 'Light Grey', price: 100}
    ],
    blush: [ // Румяна//-
        {id: 255, name: "No", price: 100},
        {id: 0, name: "Full", price: 100},
        {id: 1, name: "Angled", price: 100},
        {id: 2, name: "Rounded", price: 100},
        {id: 3, name: "Horizontal", price: 100},
        {id: 4, name: "On the Cheekbones", price: 100},
        {id: 5, name: "Pretty Woman", price: 100},
        {id: 6, name: "80's Style", price: 100},
    ],
    eyesmakeup: [//-
        {id: 255, name: "No", price: 100},
        {id: 0, name: "Smokey Black", price: 100},
        {id: 1, name: "Bronze", price: 100},
        {id: 2, name: "Soft Grey", price: 100},
        {id: 3, name: "Retro Glamour", price: 100},
        {id: 4, name: "Natural", price: 100},
        {id: 5, name: "Cats's Eyes", price: 100},
        {id: 6, name: "Chick", price: 100},
        {id: 7, name: "Vamp", price: 100},
        {id: 8, name: "Vinewood Glamour", price: 100},
        {id: 9, name: "Bubblegum", price: 100},
        {id: 10, name: "Dream of the Sea", price: 100},
        {id: 11, name: "Pin-up", price: 100},
        {id: 12, name: "Purple Passion", price: 100},
        {id: 13, name: "Smokey Cat's Eyes", price: 100},
        {id: 14, name: "Fiery Ruby", price: 100},
        {id: 15, name: "Pop", price: 100},
        {id: 16, name: "Mascara", price: 100},
        {id: 17, name: "Blood Tears", price: 100},
        {id: 18, name: "Heavy Metal", price: 100},
        {id: 19, name: "Sadness", price: 100},
        {id: 20, name: "Prince of Darkness", price: 100},
        {id: 21, name: "Rocker", price: 100},
        {id: 22, name: "Goth", price: 100},
        {id: 23, name: "Punk", price: 100},
        {id: 24, name: "Contrition", price: 100},
    ],
    lipstick: [
        {id: 255, name: "No", price: 100},
        {id: 0, name: "Matte", price: 100},
        {id: 1, name: "Shiny", price: 100},
        {id: 2, name: "Contour, Matte", price: 100},
        {id: 3, name: "Contour, Shiny", price: 100},
        {id: 4, name: "Bold Outline, Matte", price: 100},
        {id: 5, name: "Bold Outline, Shiny", price: 100},
        {id: 6, name: "Unpainted, Contour, Matte", price: 100},
        {id: 7, name: "Unpainted, Contour, Shiny", price: 100},
        {id: 8, name: "Smudged Lipstick", price: 100},
        {id: 9, name: "Geisha", price: 100}
    ]
}