using System.Collections.Generic;
using NeptuneEvo.BattlePass.Models;
using NeptuneEvo.Chars;
using NeptuneEvo.Chars.Models;
using NeptuneEvo.Database.Models;

namespace NeptuneEvo.BattlePass.Season4Models
{
    public static class Repository
    {
               
        public static readonly List<BattlePassTask> BattlePassTask = new List<BattlePassTask>
        {
	        new BattlePassTask(0, "Take part in the Gun Game", 1, 5, "Let's go out.", "An unusual assignment", 777, BattlePassRewardDiff.Medium),
			new BattlePassTask(1, "Buy a weapon modification in Gun Shop", 1, 3, "Weapon customization", "Easy task", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(2, "Driving five miles with a passenger as a cab driver", 5, 5, "Cab Driver Jr.", "An unusual assignment", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(3, "Play Sapper (F9)", 1, 4, "Bomb has been defused", "An unusual assignment", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(4, "Playing slot machines in a casino", 1, 5, "Three axes", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(5, "Top up your bank account for $10 at an ATM", 1, 4, "Money", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(6, "Buy a lottery ticket at 24/7", 1, 4, "Lucky?", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(7, "Resuscitate a person with a first aid kitи", 1, 6, "I need a medic!", "Сложное задание", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(8, "Buy any clothes at Clothes Shop", 1, 4, "Fashion Verdict", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(14, "Give someone money", 1, 3, "Bring money to Mom!", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(15, "Buy the pill from the doctor in EMS", 1, 7, "Doctor!!!", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(18, "Get a tattoo on any part of your body", 1, 6, "Ringmaster, tattoo me...", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(19, "Fill up 20 liters of fuel at the gas station", 1, 5, "Fill up my tank", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(20, "Take 10 parcels while working as a letter carrier", 10, 16, "Mail for you!", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(21, "Run 80 tags while working as a lawnmower", 80, 10, "Racer illegal", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(22, "Fix 40 Electrical Units while working as an Electrician", 40, 13, "Fixer", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(23, "Launch Fireworks", 1, 5, "My Art is a Blast!", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(24, "Come to the call working as a mechanic", 1, 8, "Pedal to the floor", "Unusual task", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(26, "Renting any vehicle", 1, 6, "Carsharing", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(27, "Wash any vehicle at the car wash", 1, 5, "Moydodir", "Easy task", 666, BattlePassRewardDiff.Easy),
			new BattlePassTask(28, "Buy any fireworks", 1, 5, "Money to the wind", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(29, "Buy beer at 24/7", 1, 5, "Bright unfiltered future...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(30, "Use paired animation", 1, 7, "Interaction is our everything.", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(32, "Shake hands with 3 people", 3, 9, "Let's meet", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(33, "Test-drive any vehicle", 1, 5, "Score from 1 to 10", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(34, "Buy any mask in the Mask Shop", 1, 6, "Masked", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(35, "Take part in a street race", 1, 6, "You haven't been in a street race in a while", "Difficult task", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(38, "Visit hunting store", 1, 5, "On the lane", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(39, "Use any ATM", 1, 4, "Enter password", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(40, "Fill the car at the gas station", 1, 4, "Full tank!", "Easy task", 350, BattlePassRewardDiff.Easy),
			new BattlePassTask(42, "Fill vehicle from canister", 1, 4, "Fill petrol", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(43, "Buy information about the house from the real estate agency", 1, 5, "Trapper with experience", "Difficult task", 2228, BattlePassRewardDiff.Hard),
			new BattlePassTask(44, "Buy something at LS Customs", 1, 5, "Car for hire", "Difficult task", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(45, "Buy a bunch of keys in 24/7", 1, 4, "Keyman", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(47, "Market tent rental", 1, 5, "Seller", "Hard task", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(48, "Buy something in the market", 1, 6, "Merchant", "Difficult task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(49, "Extend tent rental at the market", 1, 6, "True Bargain!", "Difficult task", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(50, "Open any 1 case", 1, 7, "Try your luck", "Difficult task", 250, BattlePassRewardDiff.Hard),
			new BattlePassTask(51, "Challenge a government employee with an NPC", 1, 7, "I need help!", "Challenging task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(53, "Shop at the Barber Shop", 1, 6, "Hey, get a haircut", "Unusual task", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(55, "Play casino", 1, 8, "Fuck***** mouth this casino!", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(56, "Repeat someone's animation through G-menu", 1, 7, "Repeat", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(57, "Buy something in the hunting store", 1, 5, "Distant store...", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(58, "Repair 3 cars while working as a mechanic", 3, 6, "Senior mechanic", "Difficult task", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(59, "Drive 15 miles with passengers while working as a cab driver", 15, 12, "Senior Bomber", "Difficult task", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(60, "Get PayDay", 1, 6, "ZPha is dripping!", "Easy task", 420, BattlePassRewardDiff.Easy),
			new BattlePassTask(61, "To eat chips", 1, 5, "Yum, yum chips...", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(62, "Call a cab 2 times", 2, 6, "TAXiiiiiiiiiiiii!", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(63, "Ride the bus and pay the fare", 1, 4, "Pass the fare", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(64, "Pass 60 marks on bus driver job", 60, 15, "Wrong turn", "Difficult task", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(65, "Challenge mechanic", 1, 5, "Fix!", "Easy task", 777, BattlePassRewardDiff.Easy),
			new BattlePassTask(66, "Drink beer", 1, 4, "Not 'Beer' but 'Dust'", "Easy task", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(67, "Smoke bong 3 times", 3, 6, "Devil's Doodle", "Hard task", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(68, "Take 5 puffs of a vape", 5, 6, "Vape not smoked, but vaporized", "Unusual task", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(69, "Smoke bong", 1, 7, "On the clock 4:20...", "Unusual task", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(70, "Use any animation 3 times", 3, 6, "Show dancing", "Easy task", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(71, "Smoke a vape once", 1, 5, "Mrs. Puff...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(72, "Make a trade with another player", 1, 8, "Functional exchange", "Unusual task", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(74, "Use voice radio", 1, 5, "Pshh. How do you hear?", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(76, "Put phone number in contacts", 1, 7, "VKontakte", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(77, "Write 3 SMS to someone who is 'online'", 3, 8, "Communication is the key to success", "Difficult task", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(78, "Edit an existing contact in the phone", 1, 8, "Hello, are you there?", "Difficult task", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(84, "Talk to the NPC at the police station", 1, 7, "This is the police", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(85, "Talk to the NPC in the hospital", 1, 7, "Medical advice", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(86, "Fasten your seatbelt", 1, 6, "Ay pain", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(87, "Open the hood of the vehicle", 1, 6, "Car Mechanic", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(88, "Get into the trunk of the vehicle", 1, 6, "Into the woods", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(89, "Point your finger somewhere 3 times", 3, 5, "Where?", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(90, "Put item in trunk", 1, 6, "Treasure on wheels", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(91, "Repair the car by working as a mechanic", 1, 8, "Mechanic", "Difficult task", 444, BattlePassRewardDiff.Hard),
			new BattlePassTask(92, "Deliver 10 bags of money while working as a collector", 10, 10, "Carrying paper money", "Challenging task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(93, "Write an advertisement on the asphalt (/action)", 1, 5, "Advertiser 228", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(94, "Heal yourself with a first aid kit", 1, 7, "Catch a first aid kit", "Unusual task", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(95, "Roll 10 miles as a cab passenger", 10, 10, "Yandex.Taxi", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(97, "Talk to any quest character", 1, 7, "Chatterbox", "Hard task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(98, "Start treatment in the hospital on the mark", 1, 6, "Treat me completely!", "Difficult task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(99, "Use item with quick slot", 1, 3, "In the wild west...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(101, "Show passport to someone", 1, 10, "Papers, Please", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(102, "Roll dice in the casino (/dice)", 1, 7, "Gambler", "Hard task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(112, "Buy vape in 24/7", 1, 6, "Vape Nation", "Easy task", 777, BattlePassRewardDiff.Easy),
			new BattlePassTask(126, "Pass the tag to the driver as a passenger", 1, 5, "Take me there!", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(129, "Visit and explore any GunShop", 1, 5, "Local wikipedia", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(130, "Buy any weapon in GunShop", 1, 6, "On scoring", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(131, "Play Tank Royale", 1, 8, "Tankers don't sleep", "Difficult task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(132, "Play in Tank Royale!", 1, 8, "Tankers koo!", "Difficult task", 550, BattlePassRewardDiff.Hard),
			new BattlePassTask(134, "Eat pizza", 1, 5, "Mmm Hawaiian...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(135, "Eat a sandwich", 1, 5, "Subway rests!", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(136, "Drink Sprunk", 1, 5, "Refreshes...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(137, "To eat a hot dog", 1, 5, "Hot dog bun", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(138, "Drink e-Cola", 1, 5, "Coca", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(139, "Smoke a joint (use drugs)", 1, 7, "4:20", "Unusual task", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(140, "Eat Burger", 1, 5, "Going to Gucci store in St. Petersburg", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(147, "Looking for a real estate agency", 1, 7, "Looking for a hut for the New Year", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(148, "Explore church and talk to priest", 1, 7, "Oh this wedding...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(149, "Learn driving school", 1, 7, "Buy a license!", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(150, "Learn Fireworks Salesman", 1, 7, "Light it up!", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(151, "Explore the warehouse with personal items", 1, 7, "Russian Post", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(152, "Explore pet vendor", 1, 7, "Make a friend", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(153, "Explore Caleb Baker at Black Market", 1, 7, "Black-Black Market", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(154, "Take away 20 parcels while working as a letter carrier", 20, 20, "Mail to you! 2.0", "Difficult task", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(155, "Pass 80 marks while working as a lawnmower", 80, 10, "Racer Illegal 2.0", "Difficult task", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(156, "Fix 80 electric boxes while working as an electrician", 80, 20, "Fiksik 2.0", "Difficult task", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(157, "Deliver 15 bags of money while working as a money collector", 15, 15, "Carrying paper money 2.0", "Difficult task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(158, "Get PayDay 2 times", 2, 15, "ZPha drip! 2.0", "Unnecessary task", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(159, "Drive 20 miles with passengers while working as a cab driver", 20, 18, "Senior Bomber 2.0", "Difficult task", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(160, "Pass 100 marks on bus driver job", 100, 20, "Wrong Turn 2.0", "Difficult task", 666, BattlePassRewardDiff.Hard),
        };

		public static List<BattlePassReward> BattlePassAwards = new List<BattlePassReward>
		{
			new BattlePassReward(0, type: BattlePassRewardType.Money, count: 1000),
            new BattlePassReward(1, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(2, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
            new BattlePassReward(3, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
            new BattlePassReward(4, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
            new BattlePassReward(7, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
			new BattlePassReward(8, type: BattlePassRewardType.Donate, count: 250),
            new BattlePassReward(9, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
            new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
            new BattlePassReward(11, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
			new BattlePassReward(12, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
            new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 1),
			new BattlePassReward(14, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(16, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
			new BattlePassReward(17, type: BattlePassRewardType.Donate, count: 250),
			new BattlePassReward(18, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
			new BattlePassReward(19, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
			new BattlePassReward(20, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1), 
			new BattlePassReward(22, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case2, count: 1),
            new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
			new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(26, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 3),
            new BattlePassReward(27, type: BattlePassRewardType.Money, count: 1000),
            new BattlePassReward(28, type: BattlePassRewardType.Donate, count: 250),
            new BattlePassReward(29, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
            new BattlePassReward(30, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
			new BattlePassReward(31, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(31, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(32, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case2, count: 1),
            new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(34, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 1),
            new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
            new BattlePassReward(36, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(38, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
            new BattlePassReward(39, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(40, type: BattlePassRewardType.Donate, count: 250),
			new BattlePassReward(41, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(41, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(42, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
			new BattlePassReward(43, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
			new BattlePassReward(45, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(46, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(47, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
            new BattlePassReward(48, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
			new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
            new BattlePassReward(50, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(50, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(51, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
			new BattlePassReward(52, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
			new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case2, count: 1), 
			new BattlePassReward(54, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(55, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
			new BattlePassReward(56, type: BattlePassRewardType.Donate, count: 250),
			new BattlePassReward(57, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(58, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
            new BattlePassReward(59, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
			new BattlePassReward(61, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
			new BattlePassReward(62, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(63, type: BattlePassRewardType.Donate, count: 250),
            new BattlePassReward(64, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(65, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
			new BattlePassReward(66, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case0, count: 1),
            new BattlePassReward(67, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1), 
			new BattlePassReward(68, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
			new BattlePassReward(69, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 1),
            new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(71, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
			new BattlePassReward(72, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
			new BattlePassReward(73, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case2, count: 1),
            new BattlePassReward(75, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
            new BattlePassReward(76, type: BattlePassRewardType.Money, count: 1000),
            new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(78, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
            new BattlePassReward(79, type: BattlePassRewardType.Donate, count: 250),
            new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
			new BattlePassReward(81, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
            new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(83, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(84, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case2, count: 1),
            new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count:3),
			new BattlePassReward(86, type: BattlePassRewardType.Money, count: 1000),
            new BattlePassReward(87, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(88, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
            new BattlePassReward(89, type: BattlePassRewardType.Money, count: 1000),
            new BattlePassReward(90, type: BattlePassRewardType.Donate, count: 250),
			new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
            new BattlePassReward(92, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(93, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case2, count: 1), 
			new BattlePassReward(95, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
            new BattlePassReward(96, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
            new BattlePassReward(97, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(98, type: BattlePassRewardType.Donate, count: 250),
            new BattlePassReward(99, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
            new BattlePassReward(101, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(101, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(102, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
            new BattlePassReward(103, type: BattlePassRewardType.Donate, count: 250),
            new BattlePassReward(104, type: BattlePassRewardType.Money, count: 1000),
            new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case2, count: 1),
            new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
			new BattlePassReward(107, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
            new BattlePassReward(108, type: BattlePassRewardType.Donate, count: 150),
			new BattlePassReward(109, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(109, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(110, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
			new BattlePassReward(112, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(113, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
            new BattlePassReward(114, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
            new BattlePassReward(115, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case1, count: 1),
            new BattlePassReward(116, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(117, type: BattlePassRewardType.Donate, count: 250),
            new BattlePassReward(118, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(120, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case2, count: 1),
            new BattlePassReward(121, type: BattlePassRewardType.Money, count: 2000),
			new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(123, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 1),
            new BattlePassReward(124, type: BattlePassRewardType.Money, count: 2000),
            new BattlePassReward(125, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "246_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(125, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "246_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(127, type: BattlePassRewardType.Donate, count: 200),
			new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case18, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case21, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(129, type: BattlePassRewardType.Donate, count: 200),
            new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
			new BattlePassReward(131, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"206gti", name:"Peugeot 206 GTI", count: 1),
		};

		public static List<BattlePassReward> BattlePassAwardsPremium = new List<BattlePassReward>
		{
            new BattlePassReward(0, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(1, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(2, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(3, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 3),
            new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 3),
            new BattlePassReward(5, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(7, type: BattlePassRewardType.Money, count: 5000),
            new BattlePassReward(8, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(9, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(11, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(11, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),

            new BattlePassReward(12, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(14, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case18, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case21, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(16, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(18, type: BattlePassRewardType.Money, count: 5000),
            new BattlePassReward(19, type: BattlePassRewardType.Money, count: 5000),
            new BattlePassReward(20, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(22, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),

            new BattlePassReward(25, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(26, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(27, type: BattlePassRewardType.Money, count: 5000),
            new BattlePassReward(28, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(29, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(29, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(30, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(31, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(32, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(34, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case18, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(34, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case21, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(36, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(37, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(38, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(39, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(39, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(40, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case18, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(40, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case21, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(41, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(42, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(42, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(43, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(45, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "246_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(45, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "246_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(46, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(47, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(48, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(50, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(50, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(51, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(52, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(53, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(54, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case2, count: 1),
            new BattlePassReward(55, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(55, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(56, type: BattlePassRewardType.Donate, count: 250),
            new BattlePassReward(57, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(57, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(58, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(59, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(60, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(61, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case2, count: 1),
            new BattlePassReward(62, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(63, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(65, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(65, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(66, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(67, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(68, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case18, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(68, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case21, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(69, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(71, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(72, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(73, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),

            new BattlePassReward(75, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case18, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(75, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case21, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(76, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(77, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(78, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(79, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(79, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(81, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(82, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(83, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "246_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(83, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "246_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(84, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(86, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(87, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(88, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(88, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(89, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(90, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case18, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case21, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(92, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(93, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(93, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(94, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(95, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(96, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(97, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(97, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(98, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
            new BattlePassReward(99, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(99, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(101, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(102, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(103, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(104, type: BattlePassRewardType.Item, itemId: (int)ItemId.HealthKit, count: 3),
            new BattlePassReward(105, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(107, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(108, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(108, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(109, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(110, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case18, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case21, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(112, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(113, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(113, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(114, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(114, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(115, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(116, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(117, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(118, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case18, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(118, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case21, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(119, type: BattlePassRewardType.Money, count: 3000),
            new BattlePassReward(120, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(120, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(121, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(123, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(124, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 1),
            new BattlePassReward(125, type: BattlePassRewardType.Money, count: 3000),

            new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case16, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case19, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case17, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case20, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(129, type: BattlePassRewardType.Donate, count: 500),
            new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(131, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, count: 1, data: "fordraptor", name:"Ford Raptor"),
		};

    }
}