export default {
    true: {
        head: [
            {name: "None", drawable: -1, texture: 0},
            {name: "Black Panama Hat", drawable: 3, texture: 1},
            {name: "Beige Panama Hat", drawable: 3, texture: 2},
            {name: "Black Hat", drawable: 5, texture: 0},
            {name: "Grey Cap", drawable: 5, texture: 1},
            {name: "Backwards Green Cap", drawable: 9, texture: 5},
            {name: "Forward Green Cap", drawable: 10, texture: 5},
            {name: "Forward Purple Cap", drawable: 10, texture: 7},
            {name: "Christmas Tree Cap", drawable: 97, texture: 0},
            {name: "Wizard Cap", drawable: 97, texture: 3},
            {name: "Bell Cap", drawable: 97, texture: 2},
        ],
        tops: [
            {name: "White T-Shirt", drawable: 0, texture: 0},
            {name: "Grey T-Shirt", drawable: 0, texture: 1},
            {name: "Black T-Shirt", drawable: 0, texture: 2},
            {name: "Yellow T-Shirt", drawable: 0, texture: 3},
            {name: "Sweatshirt", drawable: 8, texture: 0},
            {name: "New Year's Sweater", drawable: 194, texture: 0},
            {name: "White Shirt", drawable: 144, texture: 0},
        ],
        legs: [
            {name: "Dark Jeans", drawable: 1, texture: 1},
            {name: "Grey Jeans", drawable: 1, texture: 2},
            {name: "Blue Jeans", drawable: 1, texture: 5},
            {name: "Dark Skinny Jeans", drawable: 4, texture: 0},
            {name: "Grey Skinny Jeans", drawable: 4, texture: 1},
            {name: "Light Skinny Jeans", drawable: 4, texture: 2},
            {name: "Beige Shorts", drawable: 15, texture: 0},
            {name: "Brown Shorts", drawable: 15, texture: 1},
            {name: "White Shorts", drawable: 15, texture: 2},
            {name: "Dark Shorts", drawable: 15, texture: 3},
        ],
        shoes: [
            {name: "Black Sneakers", drawable: 1, texture: 0},
            {name: "White Sneakers", drawable: 1, texture: 1},
            {name: "Red Sneakers", drawable: 1, texture: 10},
            {name: "Brown Shoes", drawable: 12, texture: 0},
            {name: "Blue Shoes", drawable: 12, texture: 2},
            {name: "Black Shoes", drawable: 12, texture: 6},
        ]
    },
    false: {
        head: [
            {name: "None", drawable: -1, texture: 0},
            {name: "Black Hat", drawable: 5, texture: 0},
            {name: "White Hat", drawable: 5, texture: 1},
            {name: "Pink Hat", drawable: 5, texture: 2},
            {name: "Dark Panama Hat", drawable: 3, texture: 7},
            {name: "Beige Cap", drawable: 10, texture: 7},
            {name: "New Years Cap", drawable: 97, texture: 0},
            {name: "New Year's hat 'Christmas tree'", drawable: 39, texture: 0},
        ],
        tops: [
            {name: "White T-shirt", drawable: 0, texture: 0},
            {name: "Pink T-shirt", drawable: 0, texture: 1},
            {name: "Black T-shirt", drawable: 0, texture: 2},
            {name: "Blue T-shirt", drawable: 0, texture: 6},
            {name: "White Polo", drawable: 14, texture: 0},
            {name: "Pink Polo", drawable: 14, texture: 1},
            {name: "Light pink polo", drawable: 14, texture: 2},
            {name: "Black Polo", drawable: 14, texture: 3},
            {name: "Christmas T-Shirt", drawable: 19, texture: 0},
        ],
        legs: [
            {name: "Light-colored jeans", drawable: 0, texture: 0},
            {name: "Dark jeans", drawable: 0, texture: 1},
            {name: "White Shorts", drawable: 10, texture: 0},
            {name: "Blue Shorts", drawable: 10, texture: 1},
            {name: "White sweatpants", drawable: 2, texture: 0},
            {name: "Grey sweatpants", drawable: 2, texture: 1},
            {name: "Black sweatpants", drawable: 2, texture: 2},
        ],
        shoes: [
            {name: "White Sneakers", drawable: 1, texture: 0},
            {name: "Dark sneakers", drawable: 1, texture: 1},
            {name: "Gray sneakers", drawable: 1, texture: 2},
            {name: "Dark shoes", drawable: 13, texture: 0},
        ]
    }
}