<script>
    //import image from '../../images/fibpolice.png'
</script>

<div class="text">
    <p><span style="font-weight: 400;">In the state, there are <strong>families</strong> and <strong>unofficial organizations. </strong>Only families can be created, while the status of an unofficial organization needs to be obtained, but we'll discuss that later. Families are established in proximity to the <strong>Eclipse Tower</strong>, where the organization's office is located.&nbsp;</span></p>
    <p><span style="font-weight: 400;">The player who creates a family must have <strong>at least the first level</strong> and <strong>$250,000</strong> in hand, and should also <strong>not have any active warnings</strong>.</span><span style="font-weight: 400;"><br /></span></p>
    <p><span style="font-weight: 400;"><strong>After creating</strong> the family, all players will receive a corresponding message in the global chat with the name of your family. You will have an <strong>office</strong> and a <strong>garage</strong> at your disposal, with the possibility of further upgrades. In addition, there will be a family chat (/fc /fcb), rank settings, and the ability to <strong>join factions!</strong></span></p>
    <p><span style="font-weight: 400;"><strong>List of upgrades:</strong></span></p>
    <p><span style="font-weight: 400;">You can purchase a <strong>personal workshop</strong> for <em>$75,000</em>, where you will be able to tune the organization's vehicles at the government price.<br /><br /></span><span style="font-weight: 400;">Buy a<strong>warehouse</strong> for <em>$50,000</em>, where it will be possible to store first-aid kits, materials, weapons and prohibited substances<br /><br /></span><span style="font-weight: 400;"><strong>Improve the office</strong><em> to level 2 or 3</em>, each level <strong>improves the interior</strong> and <strong>opens 5 additional slots in the garage</strong>.<br /><br /></span><span style="font-weight: 400;"><strong>Buy weapon blueprints</strong>, the cost of blueprints starts <em>from $5,000 and goes up to $20,000</em> Once you purchase the blueprint, members of your organization will be able to create that weapon.<br /><br /></span></p>
    <p><span style="font-weight: 400;">Now let's move on to <strong>unofficial organizations, </strong>Obtaining this status is not that simple. You need to have a team, write an SS (situation screenshot) on the forum, have a high activity on the server, and not have serious violations on your account. Once your SS is approved, you will automatically receive the new status! After that, you will have such possibilities as</span><span style="font-weight: 400;">: <strong><em>stealing weapons</em>, <em>putting a bag over the head</em>, <em>leading a player</em>, <em>use zip ties</em>, <em>create ammo</em>, <em>rob houses and cars</em>.<br /><br /></strong></span><span style="font-weight: 400;"><strong>Also</strong> if you want to create a full-fledged RP organization, you should read the topic &ldquo;<strong>Rules for Unofficial Organizations</strong>&rdquo; on our forum!</span></p>
</div>