export const FractionRankToAccess = {
    "Gov": 1,
    "TakeGuns": 2,
    "Warg": 3,
    "Ems": 4,
    "OpenWeaponStock": 5,
    "OpenStock": 6,
    "SetRank": 7,
    "Invite": 8,
    "UnInvite": 9,
    "Ticket": 10,
    "Arrest": 11,
    "Rfp": 12,
    "Follow": 13,
    "Su": 14,
    "InCar": 15,
    "Pull": 16,
    "TakeGunLic": 17,
    "TakeHelLic": 18,
    "TakePlaneLic": 19,
    "GiveGunLic": 20,
    "StealGuns": 21,
    "Pocket": 22,
    "GivePmLic": 23,
    "GiveMedLic": 24,
    "Medkit": 25,
    "Heal": 26,
    "Dep": 27,
    "TakeMats": 28,
    "TakeDrugs": 29,
    "TakeMoney": 30,
    "TakeMedkits": 31,
    "TakeStock": 32,
    "Capture": 33,
    "BuyDrugs": 34,
    "Delad": 35,
    "BizWar": 36,
    "Cuff": 37,
    "SetVehicleRank": 38,
    "DoorControl": 39,

    "TableWall": 40,
    "EditAllTabletWall": 41,
    "OrgTuning": 42,
    "OrgBuyCars": 43,
    "OrgSellCar": 44,
    "OrgUpgrate": 45,
    "OrgCrime": 46,

    "Logs": 47,
    "Reprimand": 48,
    "Dron": 49,
    "Ads": 50,
    
    "CaptureJoin": 51,
    "BizwarJoin": 52,

    "VehicleTicket": 53,
    "StartLiveStream": 62,

}

export const FractionRankToAccessName = {
    "Gov": "State wave",
    "TakeGuns": "Seizure of weapons",
    "Warg": "Emergency Mode",
    "Ems": "Receiving a call",
    "OpenWeaponStock": "Open a weapons depot",
    "OpenStock": "Warehouse management",
    "SetRank": "Rank settings",
    "Invite": "Invitation to the faction",
    "UnInvite": "Dismissal from the faction",
    "Ticket": "Issuing a fine",
    "Arrest": "Arrest of a man",
    "Rfp": "Release from the penitentiary",
    "Follow": "Leading the way",
    "Su": "Issuing a wanted notice",
    "InCar": "Cramming into the car",
    "Pull": "Pulling out of the car",
    "TakeGunLic": "Withdrawal of a gun license",
    "TakeHelLic": "Withdrawal of a helicopter license",
    "TakePlaneLic": "Withdrawal of an airplane license",
    "GiveGunLic": "Issuance of a gun license",
    "StealGuns": "Theft of a weapon",
    "Pocket": "Pockets searched",
    "GivePmLic": "Issuance of a paramedic's license",
    "GiveMedLic": "Issuance of a medical license",
    "Medkit": "Sale of first aid kits",
    "Heal": "Treatment of Man",
    "Dep": "Department wave",
    "TakeMats": "Taking of materials",
    "TakeDrugs": "Taking Drugs",
    "TakeMoney": "The Taking of Money",
    "TakeMedkits": "Taking first-aid kits",
    "TakeStock": "Taking from the warehouse",
    "Capture": "By nailing the hood",
    "BuyDrugs": "Buying drugs",
    "Delad": "Deleting ads",
    "BizWar": "Stabbing the bison",
    "Cuff": "Use of handcuffs and ties",
    "SetVehicleRank": "Changing vehicle ranks",
    "DoorControl": "Door control",
    "StartLiveStream":"Access to airwaves",
    "TableWall": "Publishing ads on a tablet",
    "EditAllTabletWall": "Manage ads in the tablet",
    "OrgTuning": "Vehicle tuning",
    "OrgBuyCars": "Purchase of transport",
    "OrgSellCar": "For sale",
    "OrgUpgrate": "Buying Upgrades",
    "OrgCrime": "Criminal acts",

    "Logs": "Access to logs",
    "Reprimand": "Issuing reprimands",

    "Dron": "Drone Control",
    "Ads": "Access to ads",
    
    "CaptureJoin": "Participation in Capt.",
    "BizwarJoin": "Participation in business",

    "VehicleTicket": "Write fines on the vehicle"
}