export default {
    false: [
        {gtaId: 0, name: 'Benjamin'},
        {gtaId: 1, name: 'Daniel'},
        {gtaId: 2, name: 'Joshua'},
        {gtaId: 3, name: 'Ноа'},
        {gtaId: 4, name: 'Andrew'},
        {gtaId: 5, name: 'Juan'},
        {gtaId: 6, name: 'Alex'},
        {gtaId: 7, name: 'Isaac'},
        {gtaId: 8, name: 'Ivan'},
        {gtaId: 9, name: 'Ethan'},
        {gtaId: 10, name: 'Vincent'},
        {gtaId: 11, name: 'Angel'},
        {gtaId: 12, name: 'Diego'},
        {gtaId: 13, name: 'Adrian'},
        {gtaId: 14, name: 'Gabriel'},
        {gtaId: 15, name: 'Michael'},
        {gtaId: 16, name: 'Santiago'},
        {gtaId: 17, name: 'Kevin'},
        {gtaId: 18, name: 'Louis'},
        {gtaId: 19, name: 'Samuel'},
        {gtaId: 20, name: 'Anthony'},        
        {gtaId: 21, name: 'Hannah'},
        {gtaId: 22, name: 'Audrey'}, //Scary as fuck
        {gtaId: 23, name: 'Jasmine'},
        {gtaId: 24, name: 'Giselle'}, //It's also frightening.
        {gtaId: 25, name: 'Amelia'},
        {gtaId: 26, name: 'Isabella'},
        {gtaId: 27, name: 'Zoya'},
        {gtaId: 28, name: 'Ava'},
        {gtaId: 29, name: 'Camilla'},
        {gtaId: 30, name: 'Violetta'},
        {gtaId: 31, name: 'Sofia'},
        {gtaId: 32, name: 'Evelina'},
        {gtaId: 33, name: 'Nicole'},
        {gtaId: 34, name: 'Ashley'},
        {gtaId: 35, name: 'Gracie'},
        {gtaId: 36, name: 'Brianna'},
        {gtaId: 37, name: 'Natalie'},
        {gtaId: 38, name: 'Olivia'},
        {gtaId: 39, name: 'Elizabeth'},
        {gtaId: 40, name: 'Charlotte'},
        {gtaId: 41, name: 'Emma'},        
        {gtaId: 42, name: 'Claude'},
        {gtaId: 43, name: 'Niko'},
        {gtaId: 44, name: 'John'},
        {gtaId: 45, name: 'Misty'},
    ],
    true: [
        {gtaId: 0, name: 'Benjamin'},
        {gtaId: 1, name: 'Daniel'},
        {gtaId: 2, name: 'Joshua'},
        {gtaId: 3, name: 'Ноа'},
        {gtaId: 4, name: 'Andrew'},
        {gtaId: 5, name: 'Juan'},
        {gtaId: 6, name: 'Alex'},
        {gtaId: 7, name: 'Isaac'},
        {gtaId: 8, name: 'Ivan'},
        {gtaId: 9, name: 'Ethan'},
        {gtaId: 10, name: 'Vincent'},
        {gtaId: 11, name: 'Angel'},
        {gtaId: 12, name: 'Diego'},
        {gtaId: 13, name: 'Adrian'},
        {gtaId: 14, name: 'Gabriel'},
        {gtaId: 15, name: 'Michael'},
        {gtaId: 16, name: 'Santiago'},
        {gtaId: 17, name: 'Kevin'},
        {gtaId: 18, name: 'Louis'},
        {gtaId: 19, name: 'Samuel'},
        {gtaId: 20, name: 'Anthony'},        
        {gtaId: 21, name: 'Hannah'},
        {gtaId: 22, name: 'Audrey'}, //Scary as fuck
        {gtaId: 23, name: 'Jasmine'},
        {gtaId: 24, name: 'Giselle'}, //It's also frightening.
        {gtaId: 25, name: 'Amelia'},
        {gtaId: 26, name: 'Isabella'},
        {gtaId: 27, name: 'Zoya'},
        {gtaId: 28, name: 'Ava'},
        {gtaId: 29, name: 'Camilla'},
        {gtaId: 30, name: 'Violetta'},
        {gtaId: 31, name: 'Sofia'},
        {gtaId: 32, name: 'Evelina'},
        {gtaId: 33, name: 'Nicole'},
        {gtaId: 34, name: 'Ashley'},
        {gtaId: 35, name: 'Gracie'},
        {gtaId: 36, name: 'Brianna'},
        {gtaId: 37, name: 'Natalie'},
        {gtaId: 38, name: 'Olivia'},
        {gtaId: 39, name: 'Elizabeth'},
        {gtaId: 40, name: 'Charlotte'},
        {gtaId: 41, name: 'Emma'},        
        {gtaId: 42, name: 'Claude'},
        {gtaId: 43, name: 'Niko'},
        {gtaId: 44, name: 'John'},
        {gtaId: 45, name: 'Misty'},
    ],
}